### ISSUE TITLE
Step 3 - publish data - reloading needed after fixing validation errors

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#1004]
When the project description was missing, a validation error is received when trying to publish. Adding the description in the same page and clicking publish doesn't remove the error and reloading is needed

<img width="1153" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/82588017/78c1138e-b451-4123-9227-019d2fbed486">

**Comment by NishaSharma14** [comment]
@NRayya , can you please check if this issue still persist? For me it works fine.

**Comment by NRayya** [comment]
There are new updates to the description field and they seem to have solved the issue. Can't reproduce anymore
