### ISSUE TITLE
Delete Team option should ask for password confirmation.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#101]
Right now the delete team option does not ask for password confirmation as it is a critical asset to delete.
and should also not allow users to delete the team if has associated studies and projects with it.

**Comment by NRayya** [comment]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/82588017/196675518-c7067122-61e8-43e3-9130-d3d7d1927500.png">

<img width="637" alt="image" src="https://user-images.githubusercontent.com/82588017/196675946-6ea418da-649d-41e5-a8ed-591ec0b31a06.png">

**Comment by NishaSharma14** [comment]
![image](https://user-images.githubusercontent.com/54287612/203007380-6c54372f-be5d-47a3-9a9c-f15a867f99a8.png)
