### ISSUE TITLE
Issues with listing samples

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#1015]
Duplicate samples with same identifier retrieved across pages in samples list

- Reported by steffen neumann

<img width="440" alt="Screenshot 2024-01-12 at 12 29 21" src="https://github.com/NFDI4Chem/nmrxiv/assets/4065285/fd692786-a575-4801-93e3-17b88b35abb5">

**Comment by NRayya** [comment]
Was tested with projects, samples, and datasets.
Closed in favor of https://github.com/NFDI4Chem/nmrxiv/issues/1036
