### ISSUE TITLE
Enable nmrXiv workspace on NMRium

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#1021]
Update the config to replace the embedded workspace with nmrXiv

Change:
https://nmrium.nmrxiv.org/?defaultEmptyMessage=loading&workspace=embeded

To:
https://nmrium.nmrxiv.org/?defaultEmptyMessage=loading&workspace=nmrxiv

**Comment by NishaSharma14** [comment]
Updated in both dev and prod.
