### ISSUE TITLE
Team member with permission owner cannot delete datasets 

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#1022]
**Describe the bug**
I have created a team and invited someone. This person got the right "owner" and I would expect this member to have the same rights as the creator of the team. If this member tries to delete a project, this person gets an ``403 This Action is Unothorized``

Interestingly, the owner has the right ``can read and/or update project, study and dataset information`` and the Collaborator has the same description. 

What is the difference between the two? BTW: Project/study/dataset -> Project/sample/spectrum/a.

My use case having someone with the same rights as the creator is to curate data on behalf of someone. I created the team, a member joins, uploads data, I curate the data and the member publishes it. After that, I leave the team as  a creator but the joined other member with permissions ``owner`` may continue in using this team.

**Expected behavior**
Member added to team as owner has the same permission level as the person who created a team.

Best,
Tillmann

**Comment by NishaSharma14** [comment]
Closing this issue for now. Please reopen if the issue still persists

**Comment by tilfischer** [comment]
I can access the project settings of a project in Team IPB Halle now:

![Screenshot 2024-01-22 104622](https://github.com/NFDI4Chem/nmrxiv/assets/85482437/d1131a9d-a3fb-4dbf-b2f9-4f4faab0a18a)

However, I cannot delete a project..

![Screenshot 2024-01-22 104655](https://github.com/NFDI4Chem/nmrxiv/assets/85482437/51ac26c1-4240-4f52-90db-5f3d99ec51c1)

..although I have the permission level "owner":

![Screenshot 2024-01-22 104553](https://github.com/NFDI4Chem/nmrxiv/assets/85482437/c74214d4-7b57-4c6b-b67a-b6b5602f8d27)
