### ISSUE TITLE
Citation -> import from DataCite

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#1026]
**Is your enhancement request related to a problem? Please describe.**
Users are allow to add citations for each project. Two use cases are to add the citation of 1) the corresponding article and 2) other corresponding datasets. 

This works well for DOIs registered with CrossRef: https://api.crossref.org/works/10.1021/acs.jnatprod.1c01035

![Bildschirmfoto 2024-01-16 um 12 19 56](https://github.com/NFDI4Chem/nmrxiv/assets/85482437/6fc00f08-2ef8-4e4b-9212-97b5d7b63e45)

This does not work for DOIs registered with DataCite: https://api.datacite.org/dois/10.22000/1865

![Bildschirmfoto 2024-01-16 um 12 20 16](https://github.com/NFDI4Chem/nmrxiv/assets/85482437/bfdcf27a-d6ba-487a-bf25-2f673661c24d)

**Describe the solution you'd like**
Import of citations should be possible via DOI with DOIs registered with CrossRef and DataCite. 

Best,
Tillmann

**Comment by tilfischer** [comment]
Is this already part of the deploy? I just tested this again for #1029 but I still cannot import with DataCite DOI e.g. https://dx.doi.org/10.22000/1865

**Comment by tilfischer** [comment]
The first is the DOI with the resolver. People add this to the address bar in their browsers to get to the landing page. The second link does not work. This is a mixed up link with the URL to the DataCite API. 

https://dx.doi.org/10.22000/1865 -> landing page

https://api.datacite.org/dois/10.22000/1865 -> gives DOI metadata via https as json

https://dx.doi.org/dois/10.22000/1865 -> mix of both, but does not work

https://api.datacite.org/10.22000/1865 -> redirects to landing page. Found this just by accident and wasn't aware that that works. However, I would not use this as a resolver.

Best,
Tillmann

**Comment by NishaSharma14** [comment]
Yes for crossref we use `https://api.crossref.org/works/<DOI>` & for Datacite I am using the same as you said <https://api.datacite.org/dois/<DOI>
So if you try looking for using  https://dx.doi.org/dois/10.22000/1865  will work now. But I will apply a fix soon to handle both https://dx.doi.org/dois/10.22000/1865 & https://dx.doi.org/10.22000/1865

**Comment by tilfischer** [comment]
Tested this again. This does not eat DataCite DOIs.

**Comment by NishaSharma14** [comment]
Sorry, The fix is not deployed to PROD yet. I will let you know once done.

**Comment by NishaSharma14** [comment]
It is deployed and should be fixed now.

[Uploading screen-capture (25).webm…]()

**Comment by tilfischer** [comment]
It is fixed. Thank you!
