### ISSUE TITLE
New citation with name already taken overwrites citation

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#1029]
**Describe the bug**
Imagine a dataset published in two different repositories. Each published dataset has its own DOI but the same name. Then, the NMR data of this datasets should get published in nmrXiv. The user adds two citations in the corresponding nmrXiv project for the two publications in two different repositories. 

If one adds a citation with a name and then adds another citation with the same name, the second citation overwrites the first.

**Expected behavior**
The second citation should be added to the list of citations regardless of any other citation with the same name.

Best,
Tillmann

**Comment by NishaSharma14** [comment]
Dear @tilfischer ,
Can you plz provide any example DOIs?

**Comment by NishaSharma14** [comment]
Thanks @tilfischer , 
Can you please test this once? It should be fixed now.

**Comment by tilfischer** [comment]
I would, but this morning I noticed that nmrXiv is incredible slow to unresponsive.

**Comment by CS76** [comment]
Bots swarmed our website to scrape data this morning. We disallowed bots for now.

**Comment by tilfischer** [comment]
I can confirm that the issue is solved. Thank you!

**Comment by tilfischer** [comment]
That was too fast. Before I can report this I need to do so more testing. However, nmrXiv is still that slow that this is almos impossible. I reopen this for now and do the test later.

**Comment by NishaSharma14** [comment]
Hi @tilfischer ,
nmrXiv prod is back & stable. Please test this once and let us know.

**Comment by tilfischer** [comment]
Tested again. It does not overwrite the previous citation anymore. However, the citation added with the same title does not get added.

**Comment by NishaSharma14** [comment]
Sorry @tilfischer , due to some deployment issue, it was properly deployed.
But it should be fixed now.
[screen-capture (27).webm](https://github.com/NFDI4Chem/nmrxiv/assets/54287612/4ae40afd-33b0-43de-9c47-d9e3d9b751a9)

**Comment by tilfischer** [comment]
Thank you! Works.
