### ISSUE TITLE
Fetching public models  detalis - limit is set up to 100

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#1036]
Using the endpoint " /api/v1/list/{model}" to get public models details results in listing no more than 100 items

<img width="681" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/82588017/01afb38d-6d6f-491b-8f94-0207f9e590e1">

**Comment by CS76** [comment]
https://nmrxiv.org/api/v1/list/datasets?per_page=2000

per_page parameter will give you control on number of items to fetch and its paginated
