### ISSUE TITLE
Creator of team is not a member of his team

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#1047]
![Screenshot 2024-01-22 104553](https://github.com/NFDI4Chem/nmrxiv/assets/85482437/ef0a0e42-455c-4fa9-a685-60964ed7b372)

The Team has four members, but the Creator of that team is not a member, although the creator did not leave the team.

**Comment by CS76** [comment]
The team creator is displayed on the top of the team's settings page (team name section). So, we didn't want to display it again in the members section. Currently, we don't allow changing the role of the team creator so adding creator to the members list doesn't make sense.

Furture work: we will enable transfer of teams between users so the creator role can be switched.

**Comment by tilfischer** [comment]
Thanks for your reply and nice to hear that the team ownership may be transferable to someone else at some later time point.

**Comment by tilfischer** [comment]
Thank you for your reply. 

For my logic, I see in the screenshot above that Toni, me, Max and Michael are members of that team and that Steffen did create the team but is not a member any more i.e. has left the team already. Reading the line below ``Team Name`` might give another impression on that, but this is still not totally clear to me. Is the creator the owner or not anymore?

To solve this, `´Team Creator`` could be changed to ``Team Owner``. This is what is also described below `´Team Name``.

Best,
Tillmann
