### ISSUE TITLE
Site wide announcements - changes / updates needed (WIP)

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#105]
- [x] Announcement seed (Default needs to be active, Date range should be dynamic - 1 month from the time the announcements are seeded)
- [x] Replace "Allows managing general notifications" text with "Manage announcements"
- [x] Use term announcements every where instead of "Announcements & notifications"
- [x] Announcement delete not working
- [x] Announcement default start should be today's date and end date is 1 week or 1 month from today
- [x] Add validation on Start and End Date
- [x] Remove notification bell icon (this will be dedicated to notifications alone)
- [x] Announcement should be displayed on the top as a banner across the complete site
- [x] Remove push notification as well
- [x] Edit modal close option not working
- [x] Edit modal cannot be closed
- [x] There should be a toggle to make announcement active / in-active

**Comment by NishaSharma14** [comment]
Branch - **side-wide-announcement**
Commit -  https://github.com/NFDI4Chem/nmrxiv/commit/7c29aa49a9580af7d7efbc3bd46e86b110cfcdbc
