### ISSUE TITLE
Transforming nmrXiv teams and their dashboards to workspaces with members

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#1052]
Dear all,

**Is your enhancement request related to a problem? Please describe.**
In nmrXiv, one can create a team and invite people to join that team. This is useful if PIs create teams, as the members they invite are less stable than the PI itself. However, these types of teams are quite inflexible as the creator of a team cannot leave the team, while another user of that team with permission level ``owner`` could continue to use that team or lets say reuse that team if the team creator leaves.

**Describe the solution you'd like**
Instead of teams with a fixed team creator and flexibility for members, one could image that the team dashboards are workspaces where people could join or leave and where the initial creator could also leave or join again but the workspace can still be reused by the other team members. People with administrative right for a team could be all owners, while collaborators and reviewers retain the permissions they currently have.

Best,
Tillmann

**Comment by CS76** [comment]
Thank you for the idea. Team transfers between users will sort the issue that you described here. Do you foresee any other use cases that couldn't be handled in the current setup? 

We want to avoid rework (focus on the NMR related aspects) of this unless there is a valid use case :)

**Comment by tilfischer** [comment]
Transferring the permission of the creator of a nmrXiv team has to someone is be a solution to that. Connected to #1047
