### ISSUE TITLE
Notification/Message for user when another user adds them to a Team on nmrXiv

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#106]
Currently, if one team owner adds new members to the team, those members will receive emails to accept the invitation. It will be nice to have the invitation shown in the nmrXiv interface as well

**Comment by NishaSharma14** [comment]
Notification feature..

**Comment by NRayya** [comment]
@NishaSharma14 
If the invitation is sent before the invited user creates an account, then it doesn't show up in the notifications when an account is created
