### ISSUE TITLE
Ordering of creators/authors in DataCite DOI metadata

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#1064]
Dear all,

**Describe the bug**
Dataset https://doi.org/10.57992/nmrxiv.p55 (ordering of creators/authors got fixed in #1030)  has DOI metadata https://api.datacite.org/dois/10.57992/nmrxiv.p55 . The corresponding article https://doi.org/10.1021/acs.jnatprod.1c01035 has metadata https://api.crossref.org/works/10.1021/acs.jnatprod.1c01035 . 

For CrossRef the ordering of authors of the article is the same as the ordering in the corresponding CrossRef metadata.

For DataCite the ordering of authors of the dataset is not the same as the ordering in the corresponding DataCite metadata.

**Expected behavior**
Same ordering of author/creators as shown in nmrXiv also in the DataCite metadata.

Best,
Tillmann

**Comment by NishaSharma14** [comment]
Dear @tilfischer ,
Did you create/publish this project before the fix of https://github.com/NFDI4Chem/nmrxiv/issues/1030 ?

**Comment by tilfischer** [comment]
Yes, got published before.

**Comment by NishaSharma14** [comment]
ok.. Can you plz send me the correct order of the authors?

**Comment by tilfischer** [comment]
The correct order is the order from the corresponding article: https://doi.org/10.1021/acs.jnatprod.1c01035 or https://api.crossref.org/works/10.1021/acs.jnatprod.1c01035 , whatever you prefer.

**Comment by NishaSharma14** [comment]
@CS76, Is there a way we can update the metadata for the already generated DOI? 
As the DOI for this project was generated before the fix of the [author's sorting issue](#1030), we might have to correct the order manually by API request.

**Comment by NishaSharma14** [comment]
Closing this in favour or #1080

**Comment by NishaSharma14** [comment]
Fixed as part of #1080
