### ISSUE TITLE
Fix failing test of teams.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#1072]
Right now its commented out to bypass the failing test.

**Comment by NishaSharma14** [comment]
@CS76 You can check here in the logs
https://github.com/NFDI4Chem/nmrxiv/actions/runs/7656253793/job/20864155104

**Comment by CS76** [comment]
Culprit was the project factory - looks like this has been fixed (url -> obfuscation_code)
```
column "url" of relation "projects" does not exist
LINE 1: ..._archived", "status", "process_logs", "location", "url", "de...``
```

<img width="689" alt="Screenshot 2024-02-02 at 17 01 32" src="https://github.com/NFDI4Chem/nmrxiv/assets/4065285/62e9d1aa-9268-466d-828f-459301ae4297">


@NishaSharma14 
Local tests are running fine. Can you confirm if this is still an issue?

**Comment by NishaSharma14** [comment]
tested and works as expected.
