### ISSUE TITLE
Error message in step 1 is misleading 

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#1088]
No sample folder > Please upload spectral data to proceed (fix error message: step 1)

![Screenshot 2024-02-28 at 19 20 52](https://github.com/NFDI4Chem/nmrxiv/assets/4065285/f0e931ea-601e-4d61-b0e6-6c803e5abc41)

**Comment by NishaSharma14** [comment]
"spectral data must be organized in folders which corresponds to given sample. PLease re-organize your data and upload once again. Please refer the link for more details."
