### ISSUE TITLE
Show the date of last update of projects instead of creation date

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#109]
The projects are sorted based on the last update, which makes it better to show that information instead/along the creation date.

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/82588017/162434434-54561910-58d1-4ad8-9edc-d22ed7441786.png">

**Comment by NishaSharma14** [comment]
![image](https://user-images.githubusercontent.com/54287612/166933781-0a990d90-ed55-4a44-a0a2-3afd58c8323e.png)
