### ISSUE TITLE
There is no way to share private projects with others

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#111]
**Describe the bug**
Private projects should be possible to be seen by other members in the project, but one can only add members to the team while it is not possible to add them to the project. And the private project is not visible to the other team members.

**To Reproduce**
1. Create a private project in a team
2. send an invitation to another account to join the team
3. The other account will not be able to see the project

**Expected behavior**
To be able to share projects with certain users within or without the team ideally. A less ideal solution is to share it with the team members.

**Comment by NRayya** [comment]
Links don't work

https://github.com/NFDI4Chem/nmrxiv/issues/235

And teams don't work

https://github.com/NFDI4Chem/nmrxiv/issues/256

**Comment by CS76** [comment]
@NRayya @NishaSharma14 Can this issue be updated with the latest release?

**Comment by NishaSharma14** [comment]
Closing in favor of #235
