### ISSUE TITLE
Unify bioschemas and datacite - Naming conventions

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#1116]
- Check with the datacite naming requests

**Comment by NRayya** [comment]
At the moment:

- project naming is identical
- study naming is identical
- Datasets: 
  - Bioschemas: "94-26-8.hmqc" (study.dataset) without the dx
  - Datacite: "94-26-8[hmqc.dx]" (study[dataset])

**Comment by CS76** [comment]
follow DataCite convention and update bioschemas
