### ISSUE TITLE
Inform the user about the required fields when creating a project

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#112]
To create a project you need to enter the project name otherwise nothing happens when you press save. When creating a team,  a message is printed telling the user to enter team name. It will be nice to have something similar for the project.

<img width="769" alt="image" src="https://user-images.githubusercontent.com/82588017/162501936-0607a1c3-6e7f-4cd8-a992-3d1c2bef6df0.png">

**Comment by NishaSharma14** [comment]
![Image](https://user-images.githubusercontent.com/54287612/169294979-50f26462-2a56-4058-a9c1-605e8e633910.png)




![Image](https://user-images.githubusercontent.com/54287612/169295139-1fde99a6-293c-4942-88c6-2bdf6e5bc104.png)
