### ISSUE TITLE
 There is no way to share private studies with others 

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#113]
**Describe the bug**
Private studies should be possible to be seen by other members in the project, but one can only add members to the team while it is not possible to add them to the project. And the private study is not visible to the other team members.

**To Reproduce**

1. Create a private project in a team
2. send an invitation to another account to join the team
3. Create a private study in the project
4. The other account will not be able to see the project or the study

**Expected behavior**
 To be able to share studies with certain users within or without the project ideally. A less ideal solution is to share it with the team members.

**Comment by NRayya** [comment]
This issue is still there as creating projects is not possible

https://github.com/NFDI4Chem/nmrxiv/issues/256

**Comment by CS76** [comment]
@NRayya @NishaSharma14 Can this issue be updated with the latest release?
