### ISSUE TITLE
Empty zip files

### ISSUE THREAD

**Issue by nuffsaz** [NFDI4Chem/nmrxiv#1179]
I was looking for some data sets for software development and found the "Classics in spectroscopy" project (p22).  I downloaded a number of data sets. Brazilein, Cnicin, Chamazulene, and Hesperidin were fine, but Abietic Acid, Amygdalin, and Betulinic Acid were problematic.  In each case a sizeable (tens of MBytes) zip file downloaded but when I tried to unpack them they just produced empty folders.  I am working on a Mac and tried unpacking them with the default Archive Utility and also with "The Unarchiver.app".  Same result in both cases.  Please could someone check that these files work as intended and let me know.

Thanks.

**Comment by NRayya** [comment]
Dear @nuffsaz 
Thanks for reporting the issue. The download function in nmrXiv downloads the whole project. When I downloaded P22 I got one zipped folder for the project and when unzipping I got 6 samples and another zipped folder that has 4 samples. 

So I confirm that there is an issue as P22 has more than 6 samples, but I didn't manage to reproduce your exact issue (empty zip files). 

Could you please provide more details about:
1. The download (did you download from the project level or the samples level)?
2.  The downloaded folder structure (perhaps some photos?)
3. Did you face the same issue with any other project?

Thanks again

**Comment by nuffsaz** [comment]
Dear Nourra,

Thanks for your quick response.  To answer your questions below:

1) I downloaded from the samples level.
2) I have attached a couple of screenshots showing the structure of the download folder(s) at the point where I downloaded.
3) I have not come across the same problem with any other project, but I have not tried all of them (obviously!)

Since reading your reply I have also tried downloading at the project level (3rd screenshot) but that gets me a zip file (49 Mbytes) that only contains the data for Abietic acid, rather than the data for all the samples in the project.

Please let me know if you need any more information that I can provide.

Kind regards,

Alan

**Comment by NRayya** [comment]
Dear @nuffsaz 
I can't see any photos in your comment. This is my email: noura.rayya@uni-jena.de . Please contact me there to arrange a call and see the issue if this works for you

**Comment by NRayya** [comment]
The issue turned out to be caused be the project containing protected folders uploaded as such to nmrXiv. To be closed in favor of #1180
