### ISSUE TITLE
Implement (bio)schema.org support

### ISSUE THREAD

**Issue by sneumann** [NFDI4Chem/nmrxiv#118]
Hi, 
this issue could serve as a meta-issue to collect information about adding support for (bio)schemas.org into nmrXiv. 
Possibly types to add could be 
[Sample](https://bioschemas.org/profiles/Sample/0.2-RELEASE-2018_11_10)
[ChemicalSubstance](https://schema.org/ChemicalSubstance) 
[MolecularEntity](https://schema.org/MolecularEntity) 
[LabProtocol](https://bioschemas.org/profiles/LabProtocol/0.6-DRAFT-2020_12_08)
[Dataset](https://bioschemas.org/profiles/Dataset/)

A suggestion would be to start with `MolecularEntity`.

Implementing this will need:
1. Some code to extract/map from the (ISA) objects to schema.org/JSON-LD objects
2. Rendering these JSON-LD into the HTML pages
3. Dumping the JSON-LD somewhere so that it can be harvested without 

It would be great to consider this early, to avoid having to shoe-horn it on later. @meier-rene has experience doing that in the Java/MassBank world. @uly55e5 can help specifying new types like (Analytical/Spectral)DataSet.

Yours,
Steffen

**Comment by NRayya** [comment]
Hi @sneumann, I was checking the suggested types, I see that [MolecularEntity](https://schema.org/MolecularEntity) can be seen as a parent set of [ChemicalSubstance](https://schema.org/ChemicalSubstance), so maybe we don't need the chemical substance? Possible uses are for molecules in a mixture, acquisition nucleus, solvent, and I think [MolecularEntity](https://schema.org/MolecularEntity) can fit them all, while  [ChemicalSubstance](https://schema.org/ChemicalSubstance) doesn't

**Comment by NRayya** [comment]
Other possible profiles: 

- [ ] [Study](https://bioschemas.org/profiles/Study/0.2-DRAFT)
- [ ] [Person](https://bioschemas.org/profiles/Person/0.2-DRAFT-2019_07_19)
- [ ] [Journal](https://bioschemas.org/profiles/Journal/0.2-DRAFT-2020_12_03)

**Comment by NRayya** [comment]
https://github.com/NFDI4Chem/nmrxiv/issues/191

**Comment by NRayya** [comment]
https://github.com/NFDI4Chem/nmrxiv/pull/387

**Comment by NRayya** [comment]
Bioschema is implemented now, more improvement after discussion for v1
https://github.com/NFDI4Chem/nmrxiv/issues/393
