### ISSUE TITLE
FileUpload - Enhance file upload UI component

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#135]
**Describe the feature**
Once the files are dragged and dropped the progress bar does not reset. The progress indicator should be moved to a separate panel at the bottom and let users to browse and upload more files simultaneously.

![image](https://user-images.githubusercontent.com/54287612/169266943-fb678ddf-21d0-4d69-b7a9-31858cc36ca2.png)

**Comment by NishaSharma14** [comment]
#133 linked

**Comment by CS76** [comment]
Fixed
