### ISSUE TITLE
FileUpload -  zip folder download option.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#136]
**Description of the feature** 
The files or folders uploaded should have the option to download (preferably as a zip).

**Comment by NRayya** [comment]
It didn't work for me 
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/82588017/180448460-25be11fa-7c53-4731-b056-d2a93825391f.png">
All the buttons in black didn't do anything

**Comment by NishaSharma14** [comment]
I am facing this error when I try to download.

![image](https://user-images.githubusercontent.com/54287612/187700157-e7a33310-1e6c-49a4-89c9-87787e3796ef.png)

**Comment by NishaSharma14** [comment]
I think right now we just have option to download the files from Study->Dataset->Files and it works fine for me.

![image](https://user-images.githubusercontent.com/54287612/194334036-3589465a-1502-445a-8dce-14ea97e719a7.png)
