### ISSUE TITLE
Make the buttons color and text uniform. 

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#137]
![image](https://user-images.githubusercontent.com/54287612/169299164-35d20172-89a9-4a66-8496-112d59654954.png)

![image](https://user-images.githubusercontent.com/54287612/169299249-7cde29c4-e646-48dc-92db-43048f366d16.png)

![image](https://user-images.githubusercontent.com/54287612/169299887-0ea4b9c9-3540-4650-aebf-52f706894b7d.png)

![image](https://user-images.githubusercontent.com/54287612/169299491-aa55bd8c-b4ab-49a1-9d7d-da7e2365e9e1.png)

![image](https://user-images.githubusercontent.com/54287612/169299579-a68ee480-116b-49e4-9bb2-816932df345e.png)

![image](https://user-images.githubusercontent.com/54287612/169299811-d5324c47-6326-480d-8a06-da4f7ec12afe.png)

![image](https://user-images.githubusercontent.com/54287612/169308388-b4572abe-786b-4880-847b-6479be6d47b3.png)

**Comment by CS76** [comment]
Action: bg-gray-800
Action Hover: hover:bg-gray-700 
Action Active: active:bg-gray-900 
Action Focus: focus:outline-none focus:border-gray-900 focus:ring focus:ring-gray-300 
Action Disabled: disabled:opacity-25

Delete:  bg-red-600
Delete Hover: hover:bg-red-500
Delete Active: active:bg-red-600
Delete Focus: focus:outline-none focus:border-red-700 focus:ring focus:ring-red-200
Delete Disabled: disabled:opacity-25

Cancel: bg-white
Cancel Hover: hover:text-gray-500
Cancel Active:  active:text-gray-800 active:bg-gray-50 
Cancel Focus: focus:outline-none focus:border-blue-300 focus:ring focus:ring-blue-200
Cancel Disabled: disabled:opacity-25

Capitalise every action, delete and cancel button text
