### ISSUE TITLE
Gather terminology service API end points and other details from the TA6

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#152]
- [x] Rocket chat group to be created for better communication
- [x] API to query terms - EFO / nmrCV
- [ ] API to submit new terms 
- [ ] API for NER 
- [ ] Test latency to use the endpoints in case of the prediction
- [x]  Test the available endpoints. 

API to submit new terms and API for NER are not available at this point

**Comment by NRayya** [comment]
https://terminology.nfdi4chem.de/ts/docs/api

**Comment by NRayya** [comment]
![Image](https://user-images.githubusercontent.com/82588017/178737449-9c761c90-cf79-43ad-91a1-4a00f6707397.png)

**Comment by NRayya** [comment]
Closed in favor of: https://github.com/NFDI4Chem/nmrxiv/issues/528
