### ISSUE TITLE
Deploy nmrML converter to the cluster

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#153]
Idea is to deploy the convert to our cluster and trigger the conversion of the input files (bruker, joel and variant) user ~ project / study / dataset and store the output to the same folder.

https://github.com/phnmnl/container-nmrmlconv

Test online: https://nmrml.org/converter

**Comment by sneumann** [comment]
I'd suggest to create a CWL wrapper for the converter, and harmonisation of the CWL definition between the converters. Yours, Steffen

**Comment by NishaSharma14** [comment]
nmrML as the export format is not yet finalized. Need to revisit once the formats are confirmed, & a CWL-based pipeline will be implemented.
