### ISSUE TITLE
Deploy Sherlock to Jena VM 

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#154]
Michael's Sherlock (CASE) will be the first tool to be integrated with in nmrXiv. To begin with, let's deploy Sherlock to Jena VM to expose the API. We can then integrate this to the Front end and test it a bit. Once all the issues are ironed out we can then add it as an optional dependency on our Helm chart and be configurable at the app level.

https://github.com/michaelwenk/sherlock

**Comment by steinbeck** [comment]
This is brilliant. Great to hear that.

**Comment by NishaSharma14** [comment]
Schedule call with Michael

**Comment by NishaSharma14** [comment]
Webservice is deployed to URZ VM accessible at https://sherlock.nmrxiv.org

**Comment by CS76** [comment]
Closing in favour of #266
