### ISSUE TITLE
Submission Workflow.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#163]
[Discussion ](https://github.com/NFDI4Chem/nmrxiv/discussions/144)

**Comment by NRayya** [comment]
It was working fine but now it isn't, I just go to upload and provide all the data and press proceed, and it keeps proceeding

**Comment by NRayya** [comment]
This is related to the following issues:
https://github.com/NFDI4Chem/nmrxiv/issues/258
https://github.com/NFDI4Chem/nmrxiv/issues/259
