### ISSUE TITLE
The proceed button on submission worklfow should be disabled until files are uploaded.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#169]
The proceed button should only be enabled when the file upload is finished.

![image](https://user-images.githubusercontent.com/54287612/177552520-277e04e1-8fd9-4d3b-ae8c-3971b8e14334.png)

**Comment by NRayya** [comment]
When the data is being uploaded it is not enabled until the upload is finished

**Comment by NishaSharma14** [comment]
Can be closed now, as we have the validation error implemented.
