### ISSUE TITLE
Extract and update license and include in download tree.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#171]
**Description of the feature** 

[ ] Extract the content of the license, update the variables and push it to the respective data model directory
[ ] Include in the download zip tree in the database

Parent #149

**Comment by NRayya** [comment]
- [ ] This should also apply to the public view of a project:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/82588017/180261503-14981c00-3fc1-411d-9c89-6e616cfaa1f5.png">

**Comment by NishaSharma14** [comment]
Closing this in favor of #788
