### ISSUE TITLE
Import NMRShiftDB data in nmrXiv

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#175]
- [x] Discuss with Stefan Kuhn regarding NMRShiftDB datasets with raw & processes files.
- [x] nmreData (check nmrium if supports nmreData imports.)
- [x] Export NMRShiftDB as nmreData or any other formats supported by nmrium.
- [x] Discuss & decide on how to group datasets into projects.
- [x] Import into nmrXiv.

**Comment by NRayya** [comment]
A project containing all molecules with experimental data from NMRShiftDB is now available for testing on the development instance of nmrXiv. This issue will be closed in favor of  #648
