### ISSUE TITLE
Mol file is not detected in the uploaded dataset

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#176]
This needs to be tested/confirmed if the mol file is automatically detected

[eugenol_97-53-0.zip](https://github.com/NFDI4Chem/nmrxiv/files/9110239/eugenol_97-53-0.zip)

**Comment by CS76** [comment]
.mol file is currently expected to be present within the Bruker output folder. We should extend this to check for mol files at the study level and apply it to all the datasets with in that particular study

**Comment by hamed-musallam** [comment]
@CS76 

if the .mol file is inside the zip file at the first level, the nmriuim will detect it and load, but what do you mean in a particular study?

**Comment by CS76** [comment]
This needs to be addressed at the nmrXiv level and pass the data to the nmrium. I added you to the issue for the follow-up. No actual tasks at the nmrium level at the moment. Thanks.

**Comment by CS76** [comment]
To be handled along with #258

**Comment by NRayya** [comment]
related to #257

**Comment by NishaSharma14** [comment]
closing in favor of #727
