### ISSUE TITLE
Generate DOIs for Datasets 

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#177]
- [x] DataCite schema requirements
- [x] Assign DOIs for public datasets
- [ ] #511
- [ ] #512

**Comment by CS76** [comment]
@okoepler @hujo91 @febach 
Could you please provide us with details on how we can generate these from our end?? API?? Sandbox to test?

**Comment by NRayya** [comment]
![image](https://user-images.githubusercontent.com/82588017/180610115-92115c33-fa5b-4da0-8e95-61bfc47e7897.png)

**Comment by NRayya** [comment]
Currently, it is possible to assign DOIs for projects and studies:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/82588017/196296314-639b047a-587f-400a-ba56-703b507d8e65.png">

**Comment by CS76** [comment]
Closing in favour of #511 and #512
