### ISSUE TITLE
Bruker datasets not loading 

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#178]
Some of the Bruker output in the following dataset is not loading.

- [ ] Find out issues with the loading spectra
- [ ] No error message (needs to be passed to the parent application)

[eugenol_97-53-0.zip](https://github.com/NFDI4Chem/nmrxiv/files/9110355/eugenol_97-53-0.zip)

**Comment by hamed-musallam** [comment]
@CS76 

this is already fixed in the current version of NMRium, once we release the new version I check again.

can you test it in the development version by dragging and dropping the Zip file and see if the loaded spectra are what you expected?

**Comment by CS76** [comment]
The following output data is not loading. no error or logs

[4.zip](https://github.com/NFDI4Chem/nmrxiv/files/9111628/4.zip)
[5.zip](https://github.com/NFDI4Chem/nmrxiv/files/9111629/5.zip)
[6.zip](https://github.com/NFDI4Chem/nmrxiv/files/9111630/6.zip)
[7.zip](https://github.com/NFDI4Chem/nmrxiv/files/9111631/7.zip)

**Comment by hamed-musallam** [comment]
@CS76 

those are 2d Fid files, this is why we do not load them, I'm discussing now with the team the proper way to deal with the case.

**Comment by hamed-musallam** [comment]
@CS76 

currently, we allow the load of the 2d fid spectra in the spectra list and show a message on the left side that we can not display fid spectra 

![image](https://user-images.githubusercontent.com/35760236/179009065-5edf899f-228c-4907-b7f3-6621bc0a5ab3.png)

**Comment by CS76** [comment]
Not sure our nmrium dev instance - https://nmriumdev.nmrxiv.org is not showing that message when we load. Will this be part of the new release ??

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/4065285/179178966-3ed3fe32-a6bc-497c-9694-83ea50b74d8f.png">

**Comment by hamed-musallam** [comment]
@CS76 

because we still use an old version of NMRium, i will let you know once i update the NMRium.

**Comment by hamed-musallam** [comment]
@CS76 

closed by [https://github.com/NFDI4Chem/nmrium-react-wrapper/commit/68c3ef9b873dea898a6a152f2a466742609ee9f1](url)
