### ISSUE TITLE
Studies and datasets needs to be sorted

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#179]
Datasets are sorted randomly which might cause some confusion to the user. Basic alphabetical sorting needs to be enabled.

**Comment by NRayya** [comment]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/82588017/196677027-8a931617-8147-41ec-b9c0-14bc8870b066.png">
They are sorted alphabetically now
