### ISSUE TITLE
Table overflow - submission component

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#181]
**Describe the bug**
Submission step3 - Study ~ Datasets table overflow issue

**Expected behavior**
apply overflow-scroll to the x axis

**Screenshots**
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/4065285/178963335-9e6a9de1-46aa-42cb-a660-fa4560cc1773.png">

**Comment by NishaSharma14** [comment]
Fixed in b2d9239a021c9bd1800de0d60f27c11db24cd879
![image](https://user-images.githubusercontent.com/54287612/179232310-ca977b60-629e-430d-ab5c-e9eeab161836.png)
