### ISSUE TITLE
Import NMR datasets from public domain

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#184]
**Description of the feature** 
Data from the following publications needs to be imported

**Implementation steps or Task**
<img width="541" alt="image" src="https://user-images.githubusercontent.com/4065285/178966119-de8808f1-9194-42b0-85a6-fd508cfb76fa.png">

**Comment by NRayya** [comment]
https://pubs.acs.org/doi/10.1021/acs.joc.0c00770

**Comment by NRayya** [comment]
The user should ask for permission before using the data
Several options for permissions are provided (abstract, full article, tables...)
Support material was not an option
Trying with the available options, organizations were not allowed to publish something on the internet
