### ISSUE TITLE
Implement smart auto grouping if there is not folder structure in the uploaded files

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#187]
Grouping of related spectral experiments is recommended to the submitters. However, it might be the case that they might upload just the spectral data, and we would like to group them to make sure that they are organised in line with the project > study > datasets hierarchy.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/4065285/178967776-0ed5c4f6-b369-45dd-9ad5-dc3bb9647348.png">

**Comment by NishaSharma14** [comment]
Closing this in favour #321
