### ISSUE TITLE
Add author field to the project and mirror it in study

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#198]

**Comment by NRayya** [comment]
DataCite properties for a Contributor (which can be an author)
- Full name 
- familyName
- givenName
- nameIdentifier (e.g., an ORCID value)
- nameIdentifierScheme (e.g., saying that this identifier is an orcid)
- schemeURI (e.g., http://orcid.org)
- affiliation (free text)

**Comment by NishaSharma14** [comment]
@NRayya From the above properties, can you please identify the fields which are required/mandatory?

**Comment by NRayya** [comment]
- Full name
- nameIdentifierScheme if the nameIdentifier was provided

**Comment by NishaSharma14** [comment]
![screen-capture (4)](https://user-images.githubusercontent.com/54287612/182899017-ee2ee3ee-c234-40dd-b2cf-1248472c7bc2.gif)

**Comment by NRayya** [comment]
It is still not mirrored in the study
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/82588017/184365034-a37f53ff-ca19-4cc4-b769-32feca1dfa08.png">

**Comment by CS76** [comment]
Close this issue if this works for the projects and create one for the study. We will pick this up after obtaining some feedback from our users.
