### ISSUE TITLE
No error message if file upload fails in submission workflow.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#199]
**Describe the bug**
There should be an error message displayed to the user if file uploads fail or the format is incompatible with the submission workflow.

**Comment by NishaSharma14** [comment]
Needs to be tested when this is implemented - #265

**Comment by NRayya** [comment]
I tried a folder with a csv file, no error message was received
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/82588017/184622356-f041a041-6497-4d78-81e9-aca3020fc3a8.png">

**Comment by NRayya** [comment]
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/82588017/184652721-40feb39b-a99f-4073-b4a9-3a66c36cf712.png">
