### ISSUE TITLE
Error messages missing when changing details of studies

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#202]
**Describe the bug**
when going to a newly uploaded study, and trying to change its privacy, the changes can't be saved without tags and description, but no error messages appear to indicate that, and saving doesn't happen

**To Reproduce**
1. Upload new studies
2. go to one of them
3. click view details
4. change the privacy
5. Save
6. Nothing happens

**Expected behavior**
a massage saying that tags or description are missing should appear, and a star indicating that those are mandatory fields should also be shown next to the fields

**Comment by NRayya** [comment]
@NishaSharma14 Do we want to have mandatory asterisk?

**Comment by NishaSharma14** [comment]
I agress this should be generic all throughout.
