### ISSUE TITLE
Ability to associate citations

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#208]
DOI based citation import to Project.

- [x] Create Citation table - Columns - DOI,Title,Abstract,Citation Text. 
- [x] Many-to-many relationship with Project with pivot user who added it.
- [x] Import Citation from DOI if not add a form to add citation manually.
URL - https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=10.1021/acs.jmedchem.5b01009&format=json&pageSize=1&resulttype=core&synonym=true
Citation Text would be combination of following field.
```
  result.title
  result.authorString
  result.journalInfo.journal.title result.journalInfo.yearOfPublication result.journalInfo.volume (result.journalInfo.issue), 
  result.pageInfo
  DOI: result.doi
```

**Comment by NRayya** [comment]
- [ ] For the manual form, replace "DOI" by "orcid"

**Comment by NRayya** [comment]
- [ ] Remove the DOI provided by default "10.1021/acs.jmedchem.5b01009", maybe replace it with grey placeholder text.

**Comment by NishaSharma14** [comment]
Make the citation card clickable and add a hyperlink https://doi.org/{doi_id};
