### ISSUE TITLE
Audit details and "Learn more about sharing link"not showing up in project details screen

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#209]
Show activity details in the project/study details view

**Comment by NishaSharma14** [comment]
Commit - ccf515b241abfc99fab8fba4c9031f90d6d0c5af

**Comment by NRayya** [comment]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/82588017/180242962-e928deb6-fcca-445f-940e-f6796345ce99.png">
Both links are there and working
