### ISSUE TITLE
Email header not loading application logo

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#210]
Header wording should be replaced by the logo

<img width="599" alt="image" src="https://user-images.githubusercontent.com/4065285/179473142-fb57c900-efa7-4506-ae52-66f5ddfc2cc9.png">

**Comment by NRayya** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/82588017/180022573-6b9cd02a-9464-4dd4-96a5-6fea845ad43b.png">

**Comment by NRayya** [comment]
I created new account today and I got this

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/82588017/180164992-0ba4ea81-1250-43c8-ad6e-9993e937b29b.png">

**Comment by CS76** [comment]
Please test it again, as I could not recreate the issue?

**Comment by NRayya** [comment]
It seems it has to do with the email account settings, in our uni email it is working, but not with gmail

**Comment by NRayya** [comment]
"If Gmail thinks a sender or message is suspicious, you won’t see images automatically. Instead, you'll be asked if you want to see the image", but I wasn't asked, and I have my settings to show all images

**Comment by CS76** [comment]
This is because of the user-email client settings. Updated the alt text to nmrXiv so incase if the image doesn't load we have the placeholder text "nmrXiv" instead of Logo

**Comment by NRayya** [comment]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/82588017/183302171-8d0e441c-a93b-435f-82c1-3c7c01a3add7.png">
