### ISSUE TITLE
Project name with in a user space needs to be unique

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#216]
Unique constraint is already applied, validations needs to be updated in the submission pipeline
Move the create new project to the action instead of doing it with in the controller

**Comment by NRayya** [comment]
It is not possible to create two projects with the same name, but the error message might look scary to the user

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/82588017/180011890-b11ddbe3-5760-49a4-b97f-43f659d14006.png">

**Comment by NRayya** [comment]
https://github.com/NFDI4Chem/nmrxiv/issues/227

**Comment by NRayya** [comment]
Currently, using "new project" button doesn't allow duplication of names and shows a clear message
<img width="825" alt="image" src="https://user-images.githubusercontent.com/82588017/180981831-94a44120-4b89-41da-80b1-a28f79607d82.png">
But trying to create a project using "upload" button and giving the same name makes the process gets stuck, and it keeps "processing"

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/82588017/180981994-140982fe-8269-4302-b020-e8bb9376ac38.png">

**Comment by NRayya** [comment]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/82588017/183218608-9cd35ca1-01af-46c1-b296-dc262dad67c4.png">
