### ISSUE TITLE
Welcome message after registering is still Lorem ipsum ..

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#220]

**Comment by CS76** [comment]
We need to finalise this. Please propose some content to the onboarding views and we will update them after the internal discussion.

**Comment by NRayya** [comment]
The message now:
Welcome! nmrXiv support scientists in their efforts to collect, store, process, analyse, disclose and re-use Nuclear Magnetic Resonance Spectroscopy research data. Ready to get started? 

nmrXiv as a part of [NFDI4Chem](https://nfdi4chem.de/), focuses on the implementation and adaptation of existing and new infrastructure, necessary to capture data early in the life cycle​ and to further manage, analyse and store associated information. Checkout [Chemotion](https://www.chemotion.net/chemotionsaurus/index.html) (Electronic Lab Notebook) or [nmrXiv CLI ](https://github.com/NFDI4Chem/nmrxiv-cli)(Command Line Interface) for a seamless integration into your Lab infrastructure.

nmrXiv is 100% open source, so you’re free to dig through the source to see exactly how it works. See something that needs to be improved? Just send us a request.
Chat bubble is on the bottom left corner or email us at [info@nmrxiv.org](mailto:info@nmrxiv.org)

 All set to get started!

Start uploading your spectral data today.

Click "Get started" and upload your data or if you want a guided tour of the dashboard press the "Dashboard Tour" button below.
