### ISSUE TITLE
No add project button in the dashboard or the projects

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#221]
When the user registers, and they want to upload datasets, this is the only possible way to create projects, as there are no buttons for creating ones. 
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/82588017/180006591-e1cb4db2-8960-4043-ae97-beb017c23b6d.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/82588017/180006675-aa661cd4-86d7-48a7-a0ef-3f876eedefa2.png">

However, once the dataset is uploaded to a project, the button "new project" appears in the dashboard.

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/82588017/180007096-687a31f9-4bf5-4e69-bffb-12a62339e8c2.png">

**Comment by CS76** [comment]
We don't want to let the user create a project manually. They need to upload data first and create the project via the guided submission (upload option). Unless we have an use case the requires this, we can close this issue.

**Comment by NRayya** [comment]
This functionality was available before so I thought it is still wanted. I close the issue

**Comment by NRayya** [comment]
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/82588017/180455774-2d961014-dc03-407a-909f-6252fd9f7d89.png">
The function is there but it only appears after creating the first project by uploading, in this case we need to remove the "add project" button

**Comment by CS76** [comment]
Closing this now. This needs to be discussed later after the beta release on how to approach the project creation.
