### ISSUE TITLE
Rename "Projects" folder to "Public projects"

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#222]
**Describe the bug**
Created projects appear only in the dashboard while they should be mainly accessible from the "Projects" folder

**To Reproduce**
1. Create a project
2. Go to the dashboard, project is there
3. go to the projects folder, nothing there

**Expected behavior**
Tp have th eproject on both places

**Screenshots**
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/82588017/180009847-ec4655ca-9bf9-4eb5-a20a-b8309d14673c.png">

**Comment by CS76** [comment]
The public projects page will display only projects with visibility public. When you create a project the default visibility is set to private and hence its not appearing in the public projects page. Please make a project public and check it.

**Comment by NRayya** [comment]
I checked it, it is working, but then we need to change the name to public projects instead of projects

**Comment by CS76** [comment]
Closing this in favour of #292
