### ISSUE TITLE
Projects folder description doesn't correspond to the content

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#223]
" Explore, analyze, and share raw spectral data and assignements. Learn more about datasets." Seems to be description of datasets.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/82588017/180010122-ecbfd7bf-f9d1-4ae3-b611-0610fc70aeec.png">

**Comment by NRayya** [comment]
I am getting this now when I go to projects
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/82588017/180458249-3a0d30cd-b0bf-4286-b8ba-a4bd01854156.png">

**Comment by CS76** [comment]
@NRayya Can you please provide more details on how to reproduce this ?? if resolved please close the issue.

**Comment by CS76** [comment]
Duplicate #271
