### ISSUE TITLE
Adding images to the project isn't working 

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#232]
**Describe the bug**
When adding an image to the project and save the changes, this gives an error.

**To Reproduce**
1. Create a project
2. Go to view details
3. upload an image
4. save
5. you get the error (bug1)
6. click outside to quit it
7. The image can't be removed (bug2)

**Screenshots**
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/82588017/180050656-8b08cbad-5660-4a53-b52b-0faf2faff7ee.png">

uploaded image (for testing)

![GettyImages-626916125-5b3a4a8046e0fb00379f682d](https://user-images.githubusercontent.com/82588017/180051303-02bd5d31-ecde-404c-b350-d5315cc735c4.jpg)

**Comment by CS76** [comment]
Enabled tmp folder write access, this should be resolved now. Ready for testing.

**Comment by NRayya** [comment]
Working fine
