### ISSUE TITLE
Replace "user name abbreviation??" by share button in the project

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#236]
- [ ] In the following image, clicking on the blue "NO" (I assume it is from NOURA user name) opens sharing window, so it is better to be replaced by "share" button or removed

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/82588017/180244446-271c4d7f-59f2-4bfe-b61f-c15851981e1e.png">

- [ ] Additionally, the sharing message is still Lorem ipsum dolor sit amet consectetur adi

**Comment by CS76** [comment]
It's is the user's/owner's profile image, and when the user's profile image is not present, we are showing their initials.

**Comment by NRayya** [comment]
But isn't supposed to be "share" instead?

**Comment by NRayya** [comment]
If not we close the issue and I open new one for the message
