### ISSUE TITLE
Warning to users are posted publicly

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#239]
Warning about published studies "This information will be displayed publicly so be careful what you share." is shown in the public project view

<img width="977" alt="image" src="https://user-images.githubusercontent.com/82588017/180251052-d2b7f9a7-7af9-4326-9953-424fa44bd6cf.png">

**Comment by NishaSharma14** [comment]
The warning is not there now.

![image](https://user-images.githubusercontent.com/54287612/194332764-a342b45b-abb9-436e-9245-57844ebb1df6.png)
