### ISSUE TITLE
Change description of sample collection protocol as there are no parameters

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#245]
The description is: "Describe your sample collection protocol. Protocol parameters can be provided below." But no fields for parameters are provided.

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/82588017/180265170-4a5bafdb-1e25-4ec6-a040-7ade3f8b803e.png">

**Comment by CS76** [comment]
Related to #244

**Comment by NRayya** [comment]
Closed in favor of #528
