### ISSUE TITLE
"View" button not clickable in study "files" 

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#251]
**Describe the bug**
Going to study, "files" tab, uploading a file and selecting the file, scrolling down, in the content field, "view" button can't be clicked.

**Screenshots**
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/82588017/180281663-feacba59-22c2-4da9-8cdf-2f6cbbfe002a.png">

**Comment by CS76** [comment]
The view option will be enabled when the other key functionality is done. Probably V1.0 or later. Closing this now.
