### ISSUE TITLE
Sharing team issues

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#253]
Team memebers added as owners can create projects but they keep processing, and when reloading the page, they show up as draft. This leads to errors when going to "projects" folder, and the project doesn't show up to the other members

**Comment by NishaSharma14** [comment]
When the new member is added as the owner, does the file upload, it fails in the last step with the error `403 This Action is Unauthorized.`
But instead, the project is created when the page is refreshed.

When another member of the same team tries to open the same project. it throws the below error.

![image](https://user-images.githubusercontent.com/54287612/184311411-d1ce97ca-d3ab-488b-ad9f-95d53fef73f5.png)

**Comment by CS76** [comment]
Can you check why the team member doesn't have a membership (technically, all team members have a membership)
