### ISSUE TITLE
submision of datasets works only for folders not for separate files

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#255]
**Describe the bug**
When uploading one jdx file and pressing proceed, it keeps proceeding

**Comment by NRayya** [comment]
This was tested on jdx and zip files

**Comment by CS76** [comment]
nmrXiv expects all the datasets to be organised into folders based on the samples. Each sample corresponds to a folder, and all the experiments performed on the sample go into that folder. We need to convey the same to the user, visually and explanatory. Create an issue on docs and here to improve the help and messages in the corresponding sections and close this.

**Comment by NRayya** [comment]
https://github.com/NFDI4Chem/nmrxiv-docs/issues/145
https://github.com/NFDI4Chem/nmrxiv/issues/321
