### ISSUE TITLE
dragging and dropping to the structure editor

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#257]
**Describe the bug**
if you are already in the study folder and you scroll to the structure editor, you can drag and drop anything there,  for  example, you can select the word "smiles" and drag and drop it there which generates some structures

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/82588017/181017752-4e0fa01a-851c-4860-9f96-eaab8eef26af.png">

**Comment by CS76** [comment]
Can you try and save these non-chemical structures and check if they are being saved?

**Comment by NRayya** [comment]
When the structure has question marks, they can't be saved, and the program gets stucked

**Comment by NishaSharma14** [comment]
closing in favor of https://github.com/NFDI4Chem/nmrxiv/issues/727
