### ISSUE TITLE
 jdf files are not proceeded 

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#259]
**Describe the bug**
 when uploading one jdf file, or a folder that has only a jdf file, they don't work (clicking proceed doesn't proceed)

**Comment by CS76** [comment]
Can you please attach some files here to test??

**Comment by NRayya** [comment]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/KUEDTG
Here there some different formats. Checking the second one, it is a zip with multiple jdf. Neither the zip, the unzipped, single jdf, or creating a new folder with one of the jdf worked

GitHub didn't allow attaching the jdf files in a comment
