### ISSUE TITLE
Blue dots in submission process are not clickable

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#261]
**Describe the bug**
The blue dots at the top are supposed to allow the user to go backwards and forwards in the steps, but actually they are not clickable.

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/82588017/181464789-bd431e8f-2d45-4acf-8407-5ebf3eee9902.png">

**Comment by CS76** [comment]
We expect users to use the "Proceed" and "Back" buttons in the footer to navigate instead of the dots. These are visual representation of the progress so far.
