### ISSUE TITLE
Collaborator has option to switch roles but when selected throws unauthorized error.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#270]
Should Collaborator have the option to switch roles?
Ans - As discussed with @CS76 , Option to switch roles should only be given to role Owner and Creator.

![image](https://user-images.githubusercontent.com/54287612/182364394-3a3d59c5-d557-452b-a6f3-2ea9f15cd55c.png)

![image](https://user-images.githubusercontent.com/54287612/182364625-2bb0400b-a0f4-4cbb-b15b-a1a7468a827d.png)

**Comment by NRayya** [comment]
Currently, this is the view for the collaborator:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/82588017/184349671-97f567bc-4004-43e4-b188-9243f4f15dac.png">

And this for the creator:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/82588017/184349721-eae64ee7-f58b-4372-92c5-58cea7f9239b.png">
