### ISSUE TITLE
Error on clicking Project button on left menu bar.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#271]
![image](https://user-images.githubusercontent.com/54287612/182364839-8499b830-3927-462a-9027-b4a40445c1d0.png)

**Comment by NRayya** [comment]
https://github.com/NFDI4Chem/nmrxiv/issues/223

**Comment by CS76** [comment]
@NishaSharma14 @NRayya Could you please provide more details on how to recreate the issue ??

**Comment by NRayya** [comment]
You click on "projects" folder :D . But it is working now

**Comment by NRayya** [comment]
When clicking "projects", I am getting projects shared with me from super admin:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/82588017/183198113-32d2bf14-c108-4fa4-857f-704daa255041.png">

**Comment by CS76** [comment]
Those are public projects. Accessible to everyone. It just happened to be from the same user at the moment. It's not shared projects.
