### ISSUE TITLE
Keywords not getting saved in Studies.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#273]
**Describe the bug**
Keywords for Studies not getting saved while creating Project.

**To Reproduce**
1. On second step of Submission workflow, click on Meta Data Tab.
2. Add keywords and click save button.

**Expected behavior**
When Project has been created go to the dashboard and open that project and particular Study. The keyword field is empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/54287612/182367953-bd4aa9ba-1a79-409c-8f76-6d8f3874c664.png)

**Comment by NRayya** [comment]
Haven't we decided not to enable the user to enter keywords on the level of the study but to make it automated? @CS76

**Comment by CS76** [comment]
That's dataset not study

**Comment by NishaSharma14** [comment]
@CS76 Is the changes merged to the dev branch? Because the bug us still there.

**Comment by CS76** [comment]
I did, but during the merge, I skillfully [😬](https://emojipedia.org/grimacing-face/) managed to remove that fragment of code and take us back into the past.

**Comment by CS76** [comment]
Commit #23b0981 fixes this

**Comment by NishaSharma14** [comment]
This still doesn't work.

**Comment by NishaSharma14** [comment]
Working as expected.
