### ISSUE TITLE
File upload get stuck when uploaded with too many files.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#274]
When we upload a large chunk of files, the file upload gets stuck in between and the loading icon appears for so long. We have to refresh the page in order to get rid of it.
Below is the error that appears in the console.

![image](https://user-images.githubusercontent.com/54287612/182578519-cf8b07cf-e301-4174-a30b-03abff2a86b0.png)

**Comment by NishaSharma14** [comment]
Duplicate #168

**Comment by CS76** [comment]
CORS issue is occurring sometimes this needs to be investigated
