### ISSUE TITLE
Submission - step 3 could show check list instead of the form again

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#275]
Similar to GitHub community standards we can display minimum information standards for the submission in step 3

<img width="913" alt="image" src="https://user-images.githubusercontent.com/4065285/182613935-15089586-e36d-4bc6-b88c-8bec95cf1ab2.png">

**Comment by CS76** [comment]
<img width="914" alt="Screenshot 2022-08-31 at 15 44 32" src="https://user-images.githubusercontent.com/4065285/187693470-12ea6aae-00e2-4e53-b9c7-51de6aeb506e.png">

**Comment by NishaSharma14** [comment]
The publish button is still enabled if the user deletes the checklist detail.

![Untitled Project - 10_6_2022, 2_55_19 PM - nmrXiv](https://user-images.githubusercontent.com/54287612/194326811-db4397e4-1b02-442a-818f-61339623d230.gif)

**Comment by NishaSharma14** [comment]
@CS76 I am getting the below error while updating details in the project.


[screen-capture (1).webm](https://user-images.githubusercontent.com/54287612/196644182-3d92deac-8952-46a8-91e5-4f94cd33d700.webm)

**Comment by NishaSharma14** [comment]
> * The publish button is still enabled if the user deletes the checklist detail.

works fine

**Comment by CS76** [comment]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/4065285/196671868-ab56f80a-9ccd-4ffd-bfb1-78f5c34acb3a.png">

Validations are now extended to visually represent the optional field details. Resolves the issues reported above
