### ISSUE TITLE
Assign NMRXiv Identifier to models

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#276]

**Comment by NRayya** [comment]
project:
<img width="116" alt="image" src="https://user-images.githubusercontent.com/82588017/196302202-b07576ed-4cd5-45a4-b72e-721d6737e1aa.png">

study:
<img width="126" alt="image" src="https://user-images.githubusercontent.com/82588017/196302238-a7f6ff8e-835c-4569-9431-47e7dac1bf0d.png">

Dataset
<img width="175" alt="image" src="https://user-images.githubusercontent.com/82588017/196302263-aef3907c-9e08-43e9-9722-1911ede3347f.png">
