### ISSUE TITLE
License tab for public projects with no license

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#282]
**Describe the bug**
using the public url of a public project, if this project doesn't have a license, moving to the license tab in the public view gives an empty page.

**Comment by CS76** [comment]
We should not allow the user to make their project/study public without associating a license.

- [ ] Validation to prevent study/project go public if there is not license associated with it

**Comment by NRayya** [comment]
I tried to make a project public without a license and I got the validation error (a message telling me to provide one)
