### ISSUE TITLE
Not able to switch role at Study level.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#283]
![image](https://user-images.githubusercontent.com/54287612/183302889-e80b80c7-848a-4217-bf5b-b4377fb65c02.png)

**Comment by NishaSharma14** [comment]
As discussed with @CS76 , When the project is already shared the option to switch roles at the Study level should be restricted and would only be allowed to perform at the Project level.
The option to switch role would only be allowed at the Study level when only particular study/studies within a project are shared by the user.

**Comment by NRayya** [comment]
When the study is shared: Changing roles is possible 
When the project is shared, the roles on the study level don't appear
<img width="573" alt="image" src="https://user-images.githubusercontent.com/82588017/183884598-4a25be32-b510-44ed-a644-b71d2ae334a5.png">
