### ISSUE TITLE
Display 2D FID spectra

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#300]
They look like this currently 
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/82588017/184140743-f47e339d-d722-48a3-8aca-c395ece3f33a.png">

**Comment by NRayya** [comment]
Maybe we need to show a message or should we simply wait until we can visualize 2D?

**Comment by NRayya** [comment]
When switching between the experiments and going back to the 2D one, the message gets shown:
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/82588017/184141920-a5247f8c-0878-4f40-bfc1-34a8c0501412.png">

**Comment by CS76** [comment]
Attach a file to test this please?

**Comment by CS76** [comment]
[#1633](https://github.com/cheminfo/nmrium/pull/1633) Should resolve this

**Comment by CS76** [comment]
> Attach a file to test this please? @NRayya

Test data: https://cloud.uni-jena.de/s/FrqPSQH38Higdzf
