### ISSUE TITLE
scrolling the spectrum scrolls the page

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#301]
in the study, when selecting an experiment and going to "Datasets", the spectrum can be viewed and the peaks can be adjusted by scrolling up and down, however the entire page goes up and down as well.

**Comment by CS76** [comment]
Can you please describe this a bit more?? What's the expected behaviour?

**Comment by NishaSharma14** [comment]
Needs to be implemented in NMRium.

**Comment by hamed-musallam** [comment]
@NishaSharma14  this bug should be fixed with the new version, can you test it at the development branch and close this ticket if it is fixed
