### ISSUE TITLE
Prevent teams to be deleted unless projects associated with the team are deleted

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#303]
We should not let the user be able to delete their team if the team has projects associated with it.

Resolves null team issue

`Attempt to read property "personal_team" on null - Projects `

**Comment by NishaSharma14** [comment]
Duplicate #101

**Comment by NRayya** [comment]
I am not allowed to delete a team that has projects associated with it.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/82588017/196676115-74919c25-4701-41e9-828c-d402a1307cac.png">

But I was also not able to delete it after deleting the projects

**Comment by NishaSharma14** [comment]
Updated the message to be more clear. For recently deleted projects, the user has to wait for a cool-off of 30 days for the project to be deleted permanently.

![image](https://user-images.githubusercontent.com/54287612/196767454-beca14bd-aec9-43c4-b789-8a7780077ea4.png)
