### ISSUE TITLE
team members are unauthorized to create a project

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#313]
when a team member (not the creator) tries the submission workflow, everything works fine until the last step when pressing "finish", then they get "error 403 unauthorized", and when refreshing, the project is actually created, but instead of seeing the dashboard, a new submission process starts.

Now if one tries to open the created project, they get this error:
<img width="1799" alt="image" src="https://user-images.githubusercontent.com/82588017/184362311-425d770b-43d2-4959-884b-7c84a13cfb06.png">
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/82588017/184362439-82d050d8-9f1e-432a-b5ad-4bd95db13324.png">

**Comment by NishaSharma14** [comment]
This works fine for me.

![Dashboard - nmrXiv (6)](https://user-images.githubusercontent.com/54287612/194315225-f6552e7b-b537-4fa3-8597-2894f68efb24.gif)
