### ISSUE TITLE
Provide visual help to the user on how to organize the samples and datasets into folders

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#321]

**Comment by NishaSharma14** [comment]
Add a link to the docs.

**Comment by NishaSharma14** [comment]
Added to doc - https://docs.nmrxiv.org/docs/submission-guides/submission/upload#manage-studies-and-datasets

Also added Need Help Link at several places

![image](https://user-images.githubusercontent.com/54287612/195600199-9294874c-da45-4c28-9280-031032971021.png)

![image](https://user-images.githubusercontent.com/54287612/195601660-d89a913e-1402-438c-a65a-d25ef96666a6.png)

![image](https://user-images.githubusercontent.com/54287612/195602184-df770e99-e61a-4b26-ac2c-02a11465461e.png)

![image](https://user-images.githubusercontent.com/54287612/195602268-4df03775-01d4-4061-8939-8559ebde8d56.png)
![image](https://user-images.githubusercontent.com/54287612/195602392-fc93597a-ddee-47db-8ad9-450b6f16b5d4.png)
