### ISSUE TITLE
Handle unprocessed or failed queues.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#329]
**Describe the bug**
Right now there is no way to handle unprocessed or failed queues. The project remains in queued state forever if the queue fails to process or pick it up.

![image](https://user-images.githubusercontent.com/54287612/184829913-d2f2397b-eff2-442c-9ad5-4900e497781f.png)

**Comment by NishaSharma14** [comment]
Linked #189

**Comment by CS76** [comment]
With the new changes in the submission process, failed job details can be accessed via the horizon dashboard, and an exception will be raised on the larabug for further debugging.
