### ISSUE TITLE
Molecules InChI overlaps with the SMILES field 

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#350]
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/82588017/185622722-14872e12-0f83-422d-b781-894ec33c0211.png">

**Comment by NRayya** [comment]
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/82588017/185623237-7baca5d8-8b70-4631-8c2e-9c35bb1742ac.png">

**Comment by NishaSharma14** [comment]
https://tailwindcss.com/docs/installation

**Comment by NRayya** [comment]
The issue is still there
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/82588017/194530300-082839b8-b48f-418f-8b56-f14070073178.png">

**Comment by CS76** [comment]
https://tailwindcss.com/docs/word-break#break-all

**Comment by CS76** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/4065285/196684127-5a6b4a80-793c-4321-b19b-391b60b4ec3d.png">

**Comment by NRayya** [comment]
It is fixed on chrome but not firefox
<img width="841" alt="image" src="https://user-images.githubusercontent.com/82588017/196697279-433e7030-104f-4b2f-9b74-d7b5328805e4.png">
