### ISSUE TITLE
Datasets not updated when the project status is updated to with "is_public" - true

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#366]
Updates of the projects/studies "is_public" flag, are not propagated to the underlying models in the hierarchy.

**Comment by NishaSharma14** [comment]
I tried to replicate this issue in my local, dev & prod site. Seems to work fine.

**Comment by NRayya** [comment]
Making a project public makes the underlying study public too partially as one can visit the study from the public view of the project, however, using the public link for the study doesn't work

**Comment by NishaSharma14** [comment]
The sharing issue can be tracked here. #43
