### ISSUE TITLE
The public view of the project shows the full name of the users instead of their usernames. 

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#369]
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/82588017/185901710-0067675f-c079-48bf-a61c-ec29fe8d0548.png">

**Comment by CS76** [comment]
We need to display the full names of the authors / Submitters. The user name is only meant for the URLs. We can display usernames below the full names if it is required.
