### ISSUE TITLE
Attempt to read property "username" on null

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#373]
When clicking on "shared with me" or "recent" from inside a team

<img width="1882" alt="image" src="https://user-images.githubusercontent.com/82588017/185991198-9d0584d9-a22a-4d8f-8580-65a21648d213.png">

**Comment by CS76** [comment]
This happens if the user's account (owner of the project) is deleted. Since user account deletion is now disabled. This should not be occurring. Please test on a new account/project and close if it doesn't reoccur.

**Comment by NishaSharma14** [comment]
Retest after resetting the database.
