### ISSUE TITLE
Submission - Authors orcid gives server error

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#405]
During the submission, when adding authors and providing their ORCID ID, it shows in blue and it is clickable, but when you click it, you get server error 500

**Comment by NishaSharma14** [comment]
@NRayya This works fine for me. Can you send me the exact steps where it is failing?

![screen-capture (3)](https://user-images.githubusercontent.com/54287612/194310958-5e40ea18-da2c-49ed-bf17-631b4e4ae1e7.gif)

**Comment by NRayya** [comment]
Hi @NishaSharma14, Before you press add and save, when you are still selecting the authors, if you click on the blue links there it will not work

**Comment by NRayya** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/82588017/194522514-14b8b36f-e06b-45e4-8263-5e1edf513660.png">

**Comment by NRayya** [comment]
The link in the suggested list is working, but the one in the selected authors is not.
![screen-capture (6)](https://user-images.githubusercontent.com/82588017/196299176-485b7c33-6838-476c-bd46-412dea77a9b3.gif)

**Comment by NRayya** [comment]
All links work now 👍
