### ISSUE TITLE
Persistent links for projects and studies

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#406]
Currently the public links for projects and studies contain their names, so when the name changes, those links don't work anymore.

The names should be replaced by the persistent identifier.

**Comment by NishaSharma14** [comment]
Linked to #276

**Comment by NRayya** [comment]
Currently, the public link to the project has its PID:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/82588017/196299360-e3138a1d-298a-4bfa-94f8-94b4229b9790.png">

Same for study:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/82588017/196299406-d4b63ce4-109d-4f0d-9405-c56fca99c0f5.png">
