### ISSUE TITLE
Notify the project owners about the delete action via email

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#423]
Once the project moved to trash, the project owner & creator would receive an email notifying them about the deletion.
User should also get reminder mail 1 week and 1 day before deleting the project permanently from storage.

**Comment by NRayya** [comment]
Confirmed: first notification about deletion received.

**Comment by NishaSharma14** [comment]
After running the Scheduler in Cluster.
 
**Confirmed: first reminder received- one week before**

![image](https://user-images.githubusercontent.com/54287612/208894728-20af3787-6f87-4be6-ac38-4e5294a4a9a2.png)

**Comment by NRayya** [comment]
Confirmed: first notification about deletion received today.

**Comment by NRayya** [comment]
First reminder today:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/82588017/209475001-4308b3ce-8e87-450e-9ab0-f0e7c5a6f287.png">

**Comment by NRayya** [comment]
Last reminder:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/82588017/210149418-edbc0c98-6ee5-4c1b-9295-9c6bd713ec7b.png">

**Comment by NRayya** [comment]
@NishaSharma14 The last reminder was the last email to be received. I believe a permanent deletion confirmation is needed too.

**Comment by NishaSharma14** [comment]
> @NishaSharma14 The last reminder was the last email to be received. I believe a permanent deletion confirmation is needed too.

I don't think so this would be required.
But can you please create a separate issue for this? We can discuss about it.
