### ISSUE TITLE
Studies - URL Sharing

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#43]
Description:
- [x] Public status - generate a unique URL with study slug
- [x] Private - offered with 2 options
- [x] Restricted - only users in the team and users with explicit study access can access it (URL - with random string ~ should not be guessable)
- [x] Link - Generate a unique link ~ grant either "Readonly", "Commentable", "Edit"

**Comment by NRayya** [comment]
The Public url of a study isn't working

**Comment by NRayya** [comment]
Private links for sharing aren't working either

**Comment by NRayya** [comment]
Private sharing has only the "viewer option"

**Comment by NRayya** [comment]
<img width="892" alt="image" src="https://user-images.githubusercontent.com/82588017/180283968-1f9e7d8b-e454-4276-9054-1d11a94fb379.png">

**Comment by NRayya** [comment]
Sharing from profile picture is working, but roles were not tested as deletion is still being implemented

**Comment by CS76** [comment]
Link-based sharing is disabled for now.
