### ISSUE TITLE
NMRium hidden analysis tab not easy to open.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#430]
**Is your enhancement request related to a problem? Please describe.**
Right now it's not easy to open the hidden analysis tab of nmrium. The user has to double-click on three dots to open which is not convenient.

![image](https://user-images.githubusercontent.com/54287612/188158352-5ffc948f-3aff-42e1-9907-0ce0603bb2f5.png)

**Comment by hamed-musallam** [comment]
@CS76 @NishaSharma14 

Can mention the reasons why it is not convenient to double-click on three dots to open the panel? What is your suggestion for a better user experience?

**Comment by NishaSharma14** [comment]
We got this feedback from one of our users who visited nmrXiv for the first time.

For anyone visiting for the first time, the three dots are not very obvious that it has a hidden panel behind them.
and also doing double click makes it more restrictive. 

We can add some icons or anything catchy to draw the user's attention so that it's not missed.
Or change the default behavior to keep the panel open instead of collapsed.
