### ISSUE TITLE
Possibility to unselect or delete studies/datasets from Projects.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#432]
**Is your feature request related to a problem? Please describe.**
There should be a possibility to unselect or delete studies/datasets from Projects before making it public.

- [ ] #486

**Comment by CS76** [comment]
- Update docs on how to delete studies and datasets
- Change the update button text to "Manage studies" and "Manage datasets"

**Comment by NishaSharma14** [comment]
(https://docs.nmrxiv.org/docs/submission-guides/submission/folder-structure#delete-files)

![image](https://user-images.githubusercontent.com/54287612/195599728-dc9a1e86-c032-4b54-b9c5-b53efcf755bd.png)

**Comment by NRayya** [comment]
it is possible to delete files during the initial submission or from "manage studies/datasets" afterwards.
