### ISSUE TITLE
Submission pipeline - Change the word "study" in step two

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#449]
In step two of submission, on the left side, we see "STUDY (4)" . Better to replace it with "Studies (total:4)"
<img width="256" alt="image" src="https://user-images.githubusercontent.com/82588017/189395577-a91931ff-62f3-4c57-a65a-f36136b4878a.png">

**Comment by CS76** [comment]
Needs discussion with a broader audience. Moving to a future release.

**Comment by NRayya** [comment]
Now we have study or studies based on the number of studies
