### ISSUE TITLE
Explicit user access

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#45]
Description: Ability to add a user who is not part of the team owning the study/project to a particular study
- [x] Define user - studies relationship
- [x] Send an invitation email
- [x] Add the study to their shared list / own workspace or add the parent project to the workspace

**Comment by NRayya** [comment]
The out of team user receives an invitation email to the study, and it can be found in "shared with me"

**Comment by NRayya** [comment]
The project sharing works too
