### ISSUE TITLE
Enhance Structure Editor - Sample chemical composition.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#451]
**Is your enhancement request related to a problem? Please describe.**
- [x] Control-Z Doesn’t work here.- no undo option.
- [x] No option to clean my sketch of the molecule. A popup help for the icons would be good.
- [x] The icons are too small.
- [x] No option to modify the structure.

**Describe the solution you'd like**
Undo option should be there or <Control-Z> to undo any operation.
![image](https://user-images.githubusercontent.com/54287612/189619752-ea8117b1-c93b-46e7-bde6-8ad34f47271d.png)

![image](https://user-images.githubusercontent.com/54287612/189622268-0f9fd48b-34b1-4424-9ffb-9c5cb9e94430.png)

![image](https://user-images.githubusercontent.com/54287612/189622335-97939956-958c-43ec-9a92-d942a8df7cb8.png)

**Comment by NishaSharma14** [comment]
Update documentation about structure editor features and add the link to "Need Help?"

**Comment by CS76** [comment]
Updated docs: https://docs.nmrxiv.org/docs/submission-guides/submission/editor/

**Comment by NRayya** [comment]
The need help link works too.
