### ISSUE TITLE
Clicking on Save button doesn't add the author.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#453]
**Describe the bug**
Clicking on the save button does not add the author.

**To Reproduce**
1. Go to the project
2. Click on Edit Author
3. Add author manually
4. Click on Save
5. Author does not get saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/54287612/189624544-62c94f22-cb9f-44a3-823f-f0e65261fa7e.png)

**Comment by NRayya** [comment]
Save is disabled before clicking add
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/82588017/196677491-2d22474d-64eb-4276-bddc-b4d633ca0725.png">
