### ISSUE TITLE
Spectra processing not getting saved.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#455]
**Describe the bug**
When I open or re-open spectra starting from my dashboard I cannot save processing although a preview of the spectrum shows prior processing.
I have a test project with two samples. I only processed the study of the first dataset. When I process the study of the second sample I do not have any button to save the progress and all processing is lost. This seems to be a general problem because every unprocessed dataset I open from my dashboard cannot be saved.
When opening a processed spectrum all processing is lost or at least not displayed although preview still shows integration

**Screenshots**
![image](https://user-images.githubusercontent.com/54287612/189628474-812e88dc-e6f0-4198-ba6b-41b367f3b893.png)

**Comment by NRayya** [comment]
Changes are saved and added to the edit history
