### ISSUE TITLE
Study star - unclickable

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#463]
**Describe the bug**
The star next to the study name cannot be clicked, also is the project is starred this will not be reflected at the study level.

**To Reproduce**
- star a project
- Go to a study within
- try to click its star
- Nothing happens

**Comment by NRayya** [comment]
Additionally, stars are not shown in the studies section of the project
<img width="1090" alt="studies" src="https://user-images.githubusercontent.com/82588017/191979132-dbe53a38-9e54-4b59-bfa4-fecb53bfe60d.png">

**Comment by NishaSharma14** [comment]
Should be resolved now.

![Dashboard - nmrXiv (9)](https://user-images.githubusercontent.com/54287612/194555418-9befc249-6c99-48dc-aaa1-6656a96ad3ad.gif)

**Comment by NRayya** [comment]
The stars are clickable now in the study, and shown in starred, but they are not shown in the project view, so the user can't find the starred studies in one project. I think we need that too.
![screen-capture](https://user-images.githubusercontent.com/82588017/195873901-67b0c43a-4ea1-4f70-8631-5d853830dfd4.gif)
