### ISSUE TITLE
public studies - possible deletion of structures

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#464]
**Describe the bug**
A public study should not be editable, but the  Sample chemical composition is still editable as it is possible to delete the structures there.
<img width="1111" alt="Screenshot 2022-09-23 at 15 35 27" src="https://user-images.githubusercontent.com/82588017/191972456-f6d844a2-0ae4-4c16-8935-81ee298e90b1.png">

**Comment by NishaSharma14** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/54287612/195853338-e542a286-0d47-40b0-8433-10990769e193.png)
