### ISSUE TITLE
Error while uploading project profile image.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#468]
**Describe the bug**
Error while uploading an image to project.

**To Reproduce**
1. Go to project
2. Click on Why Can't I publish?
3. Click on add project profile image
4. Add image and click on Save
5. Gets below error

![image](https://user-images.githubusercontent.com/54287612/192805910-994947ee-7233-460a-a339-6796a24ff3f2.png)

**Expected behavior**
Image upload should be successfull.

**Comment by CS76** [comment]
Seems like an issue with filesize or format. Whats the size of the file being uploaded ?? Could you please attach the file here for testing purposes?

**Comment by NRayya** [comment]
works for me
