### ISSUE TITLE
citation import form DOI - wrong articles fetched

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#470]
Entering the DOI for an NMReData I got a covid article. This doesn't happen with all articles
<img width="901" alt="image" src="https://user-images.githubusercontent.com/82588017/193148810-337a8ac3-c775-480e-bbc4-fa48d68d703a.png">

**Comment by CS76** [comment]
EuropePMC search first result don't necessarily need to match the searched DOI precisely because we are searching DOI as free text. So, to avoid this issue, we have to get more results say 5 and then check each result for the exact DOI match and display the result.

**Comment by CS76** [comment]
Here is the updated query for specific term search (DOI)

https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=DOI%3A10.1002/mrc.4737&format=json

**Comment by NRayya** [comment]
The stars are clickable now, but they are not shown in the project view, so only the user can see them when the open the study, which makes the stars not useful
[screen-capture.webm](https://user-images.githubusercontent.com/82588017/195872812-dba31e1f-a90b-466b-be53-c327b49ed779.webm)

**Comment by NRayya** [comment]
in the citation section, the right article is fetched now. However, in the "authors" section, when using an article doi, still only the first article fetched which doesn't suggest the right authors. When using the author orcid, a list is given where the orcids are not identical to the search query, but the right orcid is found in this list
