### ISSUE TITLE
Color / Starred / Dormant / Archive mode

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#48]
Description: Implement the following options in the study details view
- [x] Ability to select a colour for the study
- [x] Star the study, so they are easily retrievable
- [x] ~~Option to archive study in the study settings page~~ (Option will be provided only for the project)
- [ ] #510
- [ ] #509

**Comment by NishaSharma14** [comment]
@CS76, The ability to color and star study work fine but we don't have the option to delete/archive Study as of now.

**Comment by NRayya** [comment]
It is also not clear what is the point of coloring as the color doesn't show up anywhere

**Comment by CS76** [comment]
Closing this in favour of #510 #509
