### ISSUE TITLE
Landing Page -  Update screenshots.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#481]
Screenshots from old version needs to be updated.

![image](https://user-images.githubusercontent.com/54287612/195319835-e0809cd7-0646-44fe-8fca-6c155ad696d6.png)

![image](https://user-images.githubusercontent.com/54287612/195319921-90fee4ff-e8e4-46d1-aa3c-ea681447242c.png)

**Comment by NRayya** [comment]
The old images are still there
