### ISSUE TITLE
starring - starred studies not shown in project view

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#487]
Currently it is possible to see whether a study is starred by opening the study or going to the project "starred". But I think this feature is most useful within the project, to find starred studies in a project, but there are no stars in the project view of studies
![screen-capture](https://user-images.githubusercontent.com/82588017/195874457-34d3c65b-c27f-4fd2-9b89-e2cf3d35af2d.gif)

**Comment by NishaSharma14** [comment]
We didn't do this intentionally, to keep the data and rendering lightweight. This would be performed at a later stage with the cache.
