### ISSUE TITLE
Docs links - need help for search

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#490]
In the studies section of a project, there is a link to learn more about studies. It should be replaced by a link to learn more about the search (search by what) when this page is there

<img width="1699" alt="image" src="https://user-images.githubusercontent.com/82588017/196189794-ab4f03e3-be0f-4df7-ad2b-4c89f332c65d.png">

**Comment by NishaSharma14** [comment]
We can add the documentation(Need help) link when we have the advance search feature and documentation for it.
