### ISSUE TITLE
project deletion - update confirmation message

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#493]
Currently, once a project is deleted, it is stored in the "Trash" folder for 30 days where the user can restore it. This should be clarified in the delete message

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/82588017/196244300-cf64d5d7-3605-4ba5-9869-0496321c3caa.png">

**Comment by NishaSharma14** [comment]
@NRayya The value for the below cool-off period should come from the .env variable named `COOL_OFF_PERIOD`.
