### ISSUE TITLE
submission pipeline - data not being saved

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#495]
submit a project 
Add keywords after the submission
click "Manage studies"
You see the submission pipeline
The added keywords are not there
![screen-capture (4)](https://user-images.githubusercontent.com/82588017/196295528-a11e859d-9ea5-4f49-b53b-10d580e2614b.gif)

**Comment by NishaSharma14** [comment]
Update the draft keyword based on the project keywords.

**Comment by NishaSharma14** [comment]
Working as expected.
