### ISSUE TITLE
UX/ UI - User roles needs to be displayed unambiguously

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#501]
If someone is added to a team as a collaborator, and they create a project in that team, currently the become owners of the project and collaborators in the team which gives them two roles. 

To reproduce:

1. Create a team
2. Invite person B as collaborator
3. Person B creates project in the team
4. click on sharing the project to check the ownerships
5. you get this: B is John:

![image](https://user-images.githubusercontent.com/82588017/196438102-fe54c8e6-2166-45d3-9944-b2fbd762be5b.png)

**Comment by NRayya** [comment]
The ownership of the project has the higher priority than the one in the team which will make "John" an owner.

We need to do us/ui fix to clarify it to the user.

**Comment by CS76** [comment]
Closing this now
