### ISSUE TITLE
Refactoring- Manage author.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#521]
Refactor manage author and citation including UI design backend update., enhance to have fewer button clicks and update records with one button click.

**Comment by NRayya** [comment]
Additionally, it is difficult to edit the authors, or deleting and adding them again, the changes don't always reflect in the project view 

https://user-images.githubusercontent.com/82588017/198578517-e86d4286-5617-4881-baab-6646e5d00626.mp4

**Comment by NRayya** [comment]
Related to this: https://github.com/NFDI4Chem/nmrxiv/issues/551

**Comment by NishaSharma14** [comment]
[screen-capture (3).webm](https://user-images.githubusercontent.com/54287612/202199960-7785e4bb-1601-4d48-95e6-06f60afa1249.webm)
