### ISSUE TITLE
Starring a shared project is throwing error

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#525]
**Describe the bug**
Cannot read properties of undefined (reading 'first_name') error is thrown in the console when we visit the starred page after starring a shared project

**To Reproduce**
1. Star a shared project
2. Go to the starred page (no projects are displayed - empty view)

**Expected behavior**
Starred projects needs to be displayed as usual

**Comment by NishaSharma14** [comment]
[screen-capture (3).webm](https://user-images.githubusercontent.com/54287612/202922969-7d20e352-b5d5-4730-b7f7-4c93c776df22.webm)
