### ISSUE TITLE
Usage of NMRium files after upload

### ISSUE THREAD

**Issue by michaelwenk** [NFDI4Chem/nmrxiv#531]
Currently, when uploading a NMRium file, the file is just stored and no further action happens.
It would make sense if the NMRium state from the file would be restored after the file upload, even when the current project/study already exists.

In case of multiple NMRium files exist, the user could select different states as an addition.

**Comment by CS76** [comment]
More details here - https://github.com/NFDI4Chem/nmrxiv/issues/649
