### ISSUE TITLE
Allow the selection and edition of a citation for a project

### ISSUE THREAD

**Issue by michaelwenk** [NFDI4Chem/nmrxiv#546]
After entering and saving a citation we are not able to select a specific one. Also there is no way to edit it.

One possibility is to select one specific citation in the list, the fields contents will be loaded and the user is able to edit and save it again.

**Comment by NishaSharma14** [comment]
@michaelwenk, you should be able to edit citations now.

[screen-capture (2).webm](https://user-images.githubusercontent.com/54287612/202424749-332c68d1-ed8b-4ae1-ba36-16f50a3f5677.webm)
