### ISSUE TITLE
Enable adding contributors to the article (not the project)

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#550]
Currently, we only have the authors and the users of the project(creator and shared with). We need to add contributors too as described in DataCite, and to provide a menu where the submitter can pick the roles. Here is a link to the needed roles (page 40) https://schema.datacite.org/meta/kernel-4.4/doc/DataCite-MetadataKernel_v4.4.pdf

**Comment by NishaSharma14** [comment]
Please test in [dev](https://dev.nmrxiv.org)
