### ISSUE TITLE
NMR data import - "Prenylated Flavonoids from the roots of Tephroisa rhodesica"

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#561]
mnova and zip files of the NMR data for various compounds that could be imported into nmrXiv. Write to the authors for approval and import the data.

https://zenodo.org/record/3891396#.Y2LLB-zMLQ1

**Comment by NRayya** [comment]
Can't publish until https://github.com/cheminfo/nmrium/issues/2031 solved

**Comment by CS76** [comment]
@NRayya Update please?

**Comment by NRayya** [comment]
Done: https://nmrxiv.org/P62
