### ISSUE TITLE
Citation text: Unclear, what this should mean.(info icon?)

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#564]
In the citation component, "Citation text" field is unclear. Need to update the component.

**Comment by NishaSharma14** [comment]
@CS76 Can you plz suggest the placeholder text for this

e.g. Magnetic resonance in chemistry : MRC 2018 56 ( 8 ) 703-715

**Comment by NishaSharma14** [comment]
![image](https://user-images.githubusercontent.com/54287612/204756757-f57cd387-e3f2-4e04-8d46-7de78a8c3c58.png)

**Comment by NishaSharma14** [comment]
Tracked here - https://github.com/NFDI4Chem/nmrxiv/issues/632
