### ISSUE TITLE
Cite this dataset, adding citation styles from main publishers in chemistry.

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#572]
Came across a new feature which provided a citation of a dataset. Users may choose between different citation styles which are APA, Harward, MLA, Vancouver, Chicago and IEEE. Other important style would be the styles from main publishers in chemistry and should be added, even if they are very similar or even identical to the ones already provided, as researchers might specifically search for a citation style form ACS or Wiley, only to mention a few. I provide some citation styles of random publishers to start with.

**ACS:** https://publish.acs.org/publish/data_policy 

Example: Arienzo, M.; Harrold, Z.; Collins, M.; Davidson, J.; Bai, X.; Sukumaran, S.; Umek, J. A Peristaltic Pump and Filter-Based Method for Aqueous Microplastic Sampling and Analysis. Dryad. 2022. DOI: 10.5061/dryad.12jm63xz4.

**Wiley:** https://authorservices.wiley.com/author-resources/Journal-Authors/open-access/data-sharing-citation/data-citation-policy.html

Example (generic): Authors; Year; Dataset title; Data repository or archive; Version (if any); Persistent identifier (e.g. DOI)

**RSC:** https://www.rsc.org/journals-books-databases/author-and-reviewer-hub/authors-information/prepare-and-format/data-sharing/#citingdata

Examle: P. Cui, D. P. McMahon, P. R. Spackman, B. M. Alston, M. A. Little, G. M. Day and A. I. Cooper, 2019, CCDC Experimental Crystal Structure Determination: 1915306, DOI: 10.5517/ccdc.csd.cc22912j

**Springer Nature:** https://support.springernature.com/en/support/solutions/articles/6000237618-add-a-data-citation-to-a-reference-list

Example: Hao, Z., AghaKouchak, A., Nakhjiri, N., Farahmand, A. Global Integrated Drought Monitoring and Prediction System (GIDMaPS) Data sets. figshare. http://dx.doi.org/10.6084/m9.figshare.853801 (2014)

Optional: A little button somewhere to copy this from the blue box to your clipboard. 

Best,
Tillmann

**Comment by NRayya** [comment]
Good evening @tilfischer 
As you mentioned earlier, maybe it is better to use "Angewandte Chemie" style to represent "Wiley" and "Nature Chemistry" to represent "Springer Nature"

However, to avoid any confusion, it would be great if you can provide examples with their sources.

**Comment by tilfischer** [comment]
Dear Noura,

We need to split between citation of data and citation of journal articles. That is not as easy to just look up, as data citations are rare compared to journal article citations. Due to a missing filter for my use case, I had to aggregate DOIs with their references via the CrossRef API and search there. In the interest of time, I only did this for one of the publishers listed and searched for repositories such as Chemotion, nmrXiv, RADAR but also figshare and dryad. I found journal articles having data citations. For recent journal articles these were compliant with the examples provided above, which are the ones specifically for data citation.s 

Please take take the ones provided above. You might use the URLs provided to check if there were some updates to their styles since November 2022 when I opened this issue.

Best,
Tillmann

**Comment by NRayya** [comment]
merged and tested in dev

**Comment by tilfischer** [comment]
Dear Noura,

I tested this in dev.nmrxiv.org and it looks good. There are some minor improvements I would see: 

1) The drop down menu could be reorganised to display ACS, RSC, Springer Nature and Wiley (in alphabetical order) first, followed by APA, Chicago, Harvard, MLA and Vancouver, which are of minor importance and use within the chemistry community. 
2) All citations are in bold face, while all templates are not in bold face. For the data citations, none of the templates contains any bold face. However, for article citations bold face is used by chemistry publishers for some part of the citation. I would suggest to not display the citations in bold face in nmrXiv.

Best,
Tillmann
