### ISSUE TITLE
Cite this dataset, semantification.

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#573]
The blueish "cite this dataset" box is already dynamic concerning project and studies. Well done!

On the project page it looks like...
![nmrXiv_cite_dataset1](https://user-images.githubusercontent.com/85482437/200332005-d62badf2-65ad-4d2e-a26b-2f6c6bc95a81.PNG)
...and provides a DOI which directs to the project.

On the study page it looks like...
![nmrXiv_cite_dataset2](https://user-images.githubusercontent.com/85482437/200331276-1c56bfc2-93d3-4b6b-b72f-95d77b6eea69.PNG)
...and provides a DOI which directs to the study. 

On the dataset page it looks like...
![nmrXiv_cite_dataset3](https://user-images.githubusercontent.com/85482437/200331684-f8e16cb5-a3ee-425c-b647-e4c16db64747.PNG)
...the same as on the study page and does provide a DOI which directs to the study.

Two suggestions for improvements: 
- The dataset might need its own DOI such as https://doi.org/10.57992/NMRXIV.P2.S3.D1. (I guess you are already working on that!)
- To improve the semantics, I would suggest to change the heading of these blue boxes from "cite this dataset" to "cite this project", "cite this study" and "cite this dataset". 

Best,
Tillmann

**Comment by NRayya** [comment]
Done:
<img width="1142" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/82588017/3666fe30-3023-465a-8e82-a69b1d177a70">
