### ISSUE TITLE
<Learn more about sharing> link not working in View details tab.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#58]
**Describe the bug**
Learn more about sharing link not working in View details tab.

**To Reproduce**
1. Login 
2. Go to any particular study.
3. Click on the View Details option in the top.
4. Click on Learn more about sharing link.
5. Not clickable.

**Expected behavior**
It should route to the proper link.

**Comment by NRayya** [comment]
This is also the case for projects.

**Comment by NishaSharma14** [comment]
Duplicate - #209
