### ISSUE TITLE
re-open submission window after canceling or simply a break

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#585]
Clicking "cancel" on the bottom right of this screen...

![nmrXiv_upload_dataset_1of3_ordering_datasets](https://user-images.githubusercontent.com/85482437/200818547-3eb54329-30ed-4787-92b8-3d793ef3e197.PNG)

...will lead to the overview of projects, where one, if logged in, might also end up accessing nmrxiv.org after having a break and closing the window (for some reason) or simply closing the tab by accident. 

![nmrXiv_upload_dataset_1of3_continue_submission_1](https://user-images.githubusercontent.com/85482437/200819206-b80c7f8c-d6c2-4a95-953e-31ceb9a7bcdd.PNG)

One might select the shown project and arrive...

![nmrXiv_upload_dataset_1of3_continue_submission_2](https://user-images.githubusercontent.com/85482437/200819266-07024bb0-4aec-444b-b3c6-eb26d09337db.PNG)

..here (and may add some data), but not here:

![nmrXiv_upload_dataset_1of3_ordering_datasets](https://user-images.githubusercontent.com/85482437/200819338-793dfedd-2f10-4781-955e-01530085c18c.PNG)

If the submission is not finished yet, 1) this windows shown should pop up again and/or 2) there could be some sort of button "continue submission", possibly somewhere in the white space on the right side of "owner" (screenshot 3) redirecting to https://nmrxiv.org/dashboard?action=submission&draft_id=[number].

Windows 10, Chrome v.107.0.5304.91.

**Comment by NishaSharma14** [comment]
[screen-capture.webm](https://user-images.githubusercontent.com/54287612/209309236-7233ed2d-ac5d-4b9f-a060-c831e771cfad.webm)
