### ISSUE TITLE
typo, layout, play icon, non-clickable datasets

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#586]
On step 2 of 3 of the process of uploading data, the following windows may appear:

![nmrXiv_upload_dataset_2of3](https://user-images.githubusercontent.com/85482437/200816415-27b2d882-da86-4c29-8fcf-14544ca90843.PNG)

- It is not clear, what the play button should be used for, but it can be clicked. If not needed, this button might be removed.
- "Meta Data" should be changed to "Metadata". 
- By my intention, the datasets to the left should be clickable, but they are not.
- Changes on the layout might avoid horizontal scroll bars with the left pane listing the studies and their datasets. 

Windows 10, Chrome v.107.0.5304.91.

**Comment by NishaSharma14** [comment]
Dear @tilfischer ,
The play button is to auto-import all the spectra at once.
And the datasets on the left are clickable. The one you click will become your active view.

[screen-capture.webm](https://user-images.githubusercontent.com/54287612/209313916-e5605d43-ed5f-4efd-8291-8da397d4dbf6.webm)
