### ISSUE TITLE
no processing data from Bruker format available via NMRrium

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#587]
In step 1 of 3 of the submission process, I uploaded and study in Bruker format having a 1H and a APT dataset. In step 2 of 3, NMRium shows the FID of the 1H but not the spectrum after processing including FT, phase correction, zero filling and apodization, which was supposedly already done by the operator of the NMR instrument and the processing data is stored in the dataset. If I open this 1H dataset with software such as MNova, the spectrum is shown as processed by the operator.

![nmrXiv_upload_dataset_2of3_re-upload_of_studies](https://user-images.githubusercontent.com/85482437/200824698-aaa2f5f0-e7e6-44e2-9a89-2367800115f1.PNG)

The processing data present in the dataset should be loaded and displayed to the user. I may start again with the processing of the data, but this is double-work and was already done before.

For comparison, this it how it looks like in MNova, after opening the same spectrum/dataset.

![nmrXiv_upload_dataset_2of3_FT_MNova](https://user-images.githubusercontent.com/85482437/200827525-65dd6890-bf36-478c-83e6-acd8b772ec53.PNG)

Windows 10, Chrome v.107.0.5304.91.

**Comment by tilfischer** [comment]
Measurement paraments are displayed in a table if one scrolls down. These parameters are not listed in NMRium in nmrXiv under "Information".

**Comment by hamed-musallam** [comment]
@NishaSharma14  @tilfischer 

can you share the file with us? so we can test from our end

**Comment by tilfischer** [comment]
The Bruker folders were already uploaded to nmrXiv, the corresponding project is named "Die Polei-Minze im Wandel der Zeiten" and currently in draft status. The whole dataset including the NMR data is also available in RADAR4Chem via https://doi.org/10.22000/785 , but RADAR is currently down for maintenance. 

It did not matter which Bruker folder I uploaded. Same also applies to the project of Linderazuelene.

**Comment by hamed-musallam** [comment]
@NRayya  @CS76 

can anyone upload the Bruker file here in this issue?

**Comment by tilfischer** [comment]
A whole folder including the spectra mentioned above was uploaded called "NMR_Bruker-FID". 

![nmrXiv_upload_dataset_2of3_mixup](https://user-images.githubusercontent.com/85482437/203361175-9aff861e-e551-4835-a54f-422296e5ca5c.PNG)

Under "select spectra" I selected uploaded datasets (spectra --> btw: Terminology change here? Isn't that the nmrXiv "dataset"? Anyhow, I like that it is called "spectra". Please keep it!)

- 16 is fine -> 1H
- 17 shows a FID (should be the 13C spectrum)
- 12 shows  a FID (should be the APT spectrum)
- 11 shows the COSY (which was folder 13 -> something was mixed up)
- 13 shows nothing
- 14 shows nothing
- 15 shows nothing

**Comment by tilfischer** [comment]
Deleted all datasets within this study and started to add datasets one after the other. Initially, I uploaded the 1H (folder 16), which gave the spectrum with the processing parameters including FT in the data in Bruker format. 

I opened "manage studies" again and add the 13C and APT (folder 17 and folder 12) at once. For both datasets (spectra) it only showed the FID spectrum but not the spectrum including processing data (with FT) available within the dataset in Bruker format. 

Hence, I decided to delete 17 and 12 again and upload them one after the other. After I deleted both folders, there is the folder 16 left, which should show the 1H spectrum. However, 16 is now annotated with "aptjmod" and shows and spectrum of an FID. I tried to compare the FID of the 1H, 13C, and APT, but none of these really fit the one shown in nmrXiv, while the parameters table in NMRium tells, that it is the FID of the APT experiment. 

![nmrXiv_upload_dataset_2of3_mixup_02](https://user-images.githubusercontent.com/85482437/203507091-db8e7d04-e6e7-4b4c-bb32-1cc30aef8b2f.PNG)

Something to mixed-up.

Best,
Tillmann

**Comment by tilfischer** [comment]
As it seems that this in connected to nmrium rather than nmrXiv, I forwarded this to cheminfo/nmrium [#2005](https://github.com/cheminfo/nmrium/issues/2005).

**Comment by tilfischer** [comment]
The question was answered in the above linked github issue with NMRium, which currently does not process the FID but only displays the existing data in the dropped folder.

This data is available in 16 but not in 17 for unknown reasons.

**Comment by tilfischer** [comment]
It turned out that it is actually the other way around. There is no processing data and nmrium has difficulties to handle this data. I close this issue in favour of #706 together with [#2005](https://github.com/cheminfo/nmrium/issues/2005), #[2046](https://github.com/cheminfo/nmrium/issues/2046) and [#2053](https://github.com/cheminfo/nmrium/issues/2053).
