### ISSUE TITLE
login via twitter and github not needed

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#588]
Login to nmrXiv.org provides three options: 1) login with nmrXiv login, 2) login with Twitter and 3) login with GitHub.

![nmrXiv_login](https://user-images.githubusercontent.com/85482437/200830337-aa7b21dd-90e9-404a-9efd-66f69f77c2d5.PNG)

This enhancement request would point on the question: What do researchers need to log in? 

Researchers would probably need to create a login which could be the nmrXiv login. Handiest would be DFN-AAI as with RADAR, which is, to my knowledge, work in process.

I could understand the possibility of login via GitHub, if there would be no nmrXiv login but only DFN-AAI (as with RADAR), as some (external) developers might not log in via DFN-AAI. However, the nmrXiv login is present, hence, login via GitHub could be omitted. Same applies to "login via Twitter".

**Comment by NishaSharma14** [comment]
Closing in favor of #157
