### ISSUE TITLE
add tooltips

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#589]
The usability of nmrXiv would certainly profit from alt texts (nearly) everywhere. Here are some initial suggestions for the landing page after log in. I marked with "?" if it is unclear to me, what something is useful for or what it should mean.

![nmrXiv_alt_text](https://user-images.githubusercontent.com/85482437/200834121-29663c7b-3e38-46d4-bfc8-55c982ffb928.PNG)

**Comment by tilfischer** [comment]
Thanks for adding this. The current toolbox says "submission guidelines" but it leads to https://docs.nmrxiv.org/ and not to https://docs.nmrxiv.org/docs/category/submission-guides. Two options: 1) Change text of toolbox to "documentation" 2) change link the the later one.

**Comment by CS76** [comment]
#589 is an example implementation. We will extend this to all other options in the UI

**Comment by NishaSharma14** [comment]
Related to #653
