### ISSUE TITLE
Public projects - sort by number of "ups"

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#591]
Currently, the number of ups the project receives doesn't have any effect seen by the users. 
<img width="1905" alt="projects-folder" src="https://user-images.githubusercontent.com/82588017/200844830-a4c959e4-4575-4835-bc1d-b41e0fdc443f.png">

Maybe we should sort the projects by number of likes?

**Comment by tilfischer** [comment]
I would like to raise the general question on the "ups":  Why is this useful? For which reason is this required?

A research data repository is a place where researchers can upload their research data and where other researchers can retrieve research data.
From my perspective it is not place where people might advertise their data to get "ups" to get an award after reaching, e.g., 100 "ups".

**Comment by CS76** [comment]
Don't connect this with likes on Facebook or Instagram. This is equivalent to stars on GitHub, where people can upvote and encourage/appreciate high-quality and complete submissions (FAIR). 

Upvotes are mainly meant to encourage chemists/submitters to provide high-quality data.

On the repository end, we need to promote and encourage projects that are FAIR. We will devise a metric that encodes various factors such as completeness of data, data quality and general interest in the project. Public interest towards a particular project can partly be contributed to the upvotes count (Projects with higher upvotes indicate that many users are interested in the project and thereby the original author/submitter is encouraged to provide more updates on the project). 

This is an effort to leverage network effects to encourage more submissions and also promote projects among several others.

**Comment by tilfischer** [comment]
Thanks for the explanations, but this is not as it seems after finding this feature. For now, it is still seems more like a "like" on facebook than a star on github. Both are chosen by someone without any criteria behind this decision.

**Comment by CS76** [comment]
As developers, we see GitHub stars as a metric for the project's popularity, reliability and quality. There is a mixed criterion when people choose to star a project. Starring a project is meant to appreciate the authors' efforts or the users' interest in the project (or both). It is also meant to be able to find the project later easily (bookmark).  Having said that, the projects without the stars don't mean they are unreliable. When the network effect comes into play at a particular stage, these stars drive developers to write good quality code and highlight this as an achievement. This will encourage other fellow developers to follow the same.

Similarly, we would like to encourage chemists to provide high-quality data, and if executed the right way, this will be a metric they could highlight in their profiles. I understand we need to highlight and present this feature on the UI better. We will work towards it.

**Comment by CS76** [comment]
Closing this now due to inactivity.
