### ISSUE TITLE
403 when opening project settings with the aim to delete a project

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#595]
I previously deleted a draft of a project, which worked fine. For anther project some weeks later I also wanted to delete a draft, but got an 403 trying to view the project settings.

![nmrXiv_delete_project_1](https://user-images.githubusercontent.com/85482437/201332868-ad3d739a-c467-41a6-9dc2-ebfaa5148903.PNG)
--> Project settings

![nmrXiv_delete_project_2](https://user-images.githubusercontent.com/85482437/201332901-92ff1469-b78b-4a4e-bfe1-d05902cf5f7e.PNG)

Any hints on that?

Windows 10, Chrome v.107.0.5304.91.

**Comment by tilfischer** [comment]
Its not a bug, as this is connected to permissions and an owner is not allowed to access the project settings. I will add more information, as soon as we have got more details on that via the account of the team creator.

**Comment by tilfischer** [comment]
Created a NFDI4Chem Lead-by-Example team was just about to add people. Following screenshot tells...

![nmrXiv_delete_project_3](https://user-images.githubusercontent.com/85482437/201343462-996b06e2-b620-4e9a-b4c2-20dc4d42d7ad.PNG)

...that an owner is allowed to read, update and delete a project, study and dataset, while deleting is not possible (anymore). If an owner can't delete a project, study and dataset, that he has the same rights as the collaborator, right?

I am the "owener" with Team "IPB Halle", but can't delete a project.

**Comment by NishaSharma14** [comment]
Duplicate #https://github.com/NFDI4Chem/nmrxiv/issues/590
