### ISSUE TITLE
open project from dashboard in separate tabs

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#617]
Having several draft project listed in the dashboard one might like to open several of them as new tabs, to easily compare something between these drafts. 

Currently, the target is "self", which is possibly the default and should be the default. However, there is no possibility to open them as new tabs by holding down STRG on Windows machines (or command on Apple machines) and selecting a project. 

Current workaround is to open a new tab for each project, open the dashboard in each tab, and select one project from each tab.

**Comment by CS76** [comment]
<img width="905" alt="Screenshot 2022-11-21 at 12 55 11" src="https://user-images.githubusercontent.com/4065285/203046760-a619172b-1d12-47bd-94f4-ee93397a9651.png">
