### ISSUE TITLE
Disallow team deletion if they own projects

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#618]
Teams deletion option should be disabled if the team owns projects/studies/spectral datasets.

**Comment by NishaSharma14** [comment]
@CS76, This is already implemented as part of https://github.com/NFDI4Chem/nmrxiv/issues/101

**Comment by CS76** [comment]
This issue is still persistent on the development site. Update the dev site code to latest if not, reset the data and also add the exception handling in case.
