### ISSUE TITLE
adding citation without citation text gives 500

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#622]
Adding a citation...

![nmrXiv_add_citation_without_citation_text](https://user-images.githubusercontent.com/85482437/203344841-94548a20-d360-480b-9038-a52bf0c75d71.PNG)

...without the citation text give:

![nmrXiv_add_citation_without_citation_text_500](https://user-images.githubusercontent.com/85482437/203344898-044b00bc-8bdf-4c94-aa26-e57bffcd1e9d.PNG).

It is also not clear what someone should add to "citation text". Should it be the citation as one would write this in a scientific publication in a scientific journal? What style should be used?

Btw: Import option to the left gives an error but this, if I remember correctly, was already addressed in another issue.

**Comment by CS76** [comment]
Also, while importing authors from DOI or ORCID iD, when there is missing affiliation data error is now thrown preventing the addition of authors.

<img width="971" alt="image" src="https://user-images.githubusercontent.com/4065285/203523926-817e120a-bacc-4d02-8f4f-2a75f6157b3d.png">

**Comment by NishaSharma14** [comment]
@CS76 Can you plz provide me the DOI that you are trying?

and for DOI(`10.1002/ciuz.201900868`) which @tilfischer is trying, we are getting empty resultist from the europemc webservice.

**Comment by tilfischer** [comment]
@NishaSharma14 : DOI 10.1002/ciuz.201900868 is not registered with [DataCite](https://commons.datacite.org/doi.org?query=10.1002%2Fciuz.201900868) but with [CrossRef](https://search.crossref.org/?from_ui=yes&q=10.1002%2Fciuz.201900868). Could this be a reason?

**Comment by NishaSharma14** [comment]
> 

Yes this could be a reason, for this case you might have to enter the details manually.

**Comment by NishaSharma14** [comment]
The above 500 error is fixed, Thanks @tilfischer for pointing it out.
