### ISSUE TITLE
adding citation with DOI as URL

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#623]
Adding the DOI as URL...

![nmrXiv_citation_DOI](https://user-images.githubusercontent.com/85482437/203347173-f48ba83a-8c9b-4997-b76f-c59d1c1cb20c.PNG)

..gives:

![nmrXiv_citation_DOI_2](https://user-images.githubusercontent.com/85482437/203347209-ec71f71d-7246-4153-98f7-0797a23b389f.PNG)

But the DOI shown there will link to https://doi.org/https://dx.doi.org/10.22000/786

Most frequently the DOI is displayed as an URL including the resolver, hence, users might add the DOI as an URL which gives this error.

**Comment by NishaSharma14** [comment]
![image](https://user-images.githubusercontent.com/54287612/203996452-94ccd2a0-aa8c-40e3-beac-d1bdaf2e089b.png)

**Comment by NishaSharma14** [comment]
For now, we have added a placeholder text as below so that the user stick to this format.

![image](https://user-images.githubusercontent.com/54287612/204004567-39842095-fd50-439e-8d5a-9e2141b59bc6.png)
