### ISSUE TITLE
download and delete datasets via Manages Studies and Files tab

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#625]
To delete datasets (spectra) within a study (of a sample) users need to navigate to "+ manage studies.

![nmrXiv_delete_study_01](https://user-images.githubusercontent.com/85482437/203503438-9f10a5c8-6978-403f-83e3-4de48d9ab939.PNG)

![nmrXiv_delete_study_02](https://user-images.githubusercontent.com/85482437/203503459-3955f2ea-710d-4459-8dfb-60ca22abb763.PNG)

Selecting the study (spectra) in the first screenshot and than navigation to the "files" tab gives a similar view:

![nmrXiv_delete_study_03](https://user-images.githubusercontent.com/85482437/203503467-8c726917-c369-4c6f-8dc0-c8d463d0fdb3.PNG)

However, it is not possible to delete files here but users are able to download data. 

Is it intentional that for the first it is only possible to delete data while for the second way it is only possible to download data? For me it is unclear, while this is the case and I would suggest to have both options (download and delete) in place for both ways to manage datasets and studies.

**Comment by NishaSharma14** [comment]
Yes, this is intentional. Since we auto-process the uploaded folders(to studies/spectral-datasets) delete has to happen through "+Manage studies" option otherwise, there will be files missing for samples/spectral datasets when deleting through the files tab.
