### ISSUE TITLE
authors: ordering of family name and given name

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#626]
The ordering of family name and given name shows cultural differences. In nmrXiv, the given name was mentioned first followed by the family name. This obviously changes, as I added a data curator to the list of authors much later than the authors of the corresponding publication and this author is shown with the family name first.

![nmrXiv_name_ordering](https://user-images.githubusercontent.com/85482437/203518288-1ac17ad0-396c-4cdf-859b-9492aa6e4474.PNG)

The cultural differences in name ordering is one reason why ORCID iD were set-up. Anyhow, I would suggest to follow the ordering convention in most of the English speaking countries out there, as nmrXiv is in English as well. Hence, I suggest to change the orderning back to [given name] [family name]..

**Comment by CS76** [comment]
Totally agree with following the ORCID iD convention in ordering the names.

**Comment by tilfischer** [comment]
I am sorry, if I didn't express the this clear enough but I didn't mean that we should follow the ORCID way to do this and I admit that I also do not know how ORCID exactly handles this.

....I looked this up: ORCID askes for the given name and family name and orders this in the way mentioned above. ORCID also have the feature to add ones "published name" in case one might prefer other name ordering. Well, one might suggest to also implement that I am not sure if we should try to make it that complicated.

**Comment by NishaSharma14** [comment]
Taken care of, Thanks @tilfischer for raising this up.

![image](https://user-images.githubusercontent.com/54287612/204004705-47e13864-04df-4737-adbe-eea2becb7646.png)
