### ISSUE TITLE
authors: roles

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#627]
While adding authors to a nmrXiv-project, a role needs to be chosen. Possible roles are: Researcher, ContactPerson, DataCollector, DataCurator, DataManger, Distributor, Editor, HostingInstitution, Producer, ProjectLeader, ProjectManager, RegistrationAgency, RelatedPerson, Researcher (again), ResearchGroup, RightsHolder, Sponsor, Supervisor, WorkPageLeader, other. It seems to me, that this list is the same as the controlled vocabulary for contributorType in the DataCite metadata schema.

This selection for creators and authors of data is a bit fussy, as someone could be a researcher but also the contact person and data collector. Discussions on possible roles were previously discussed with other NFDI4Chem repos, hence, we do not need to re-invent the wheel. 

One possible way to tackle the role issue is to separate into 1) Creators and Authors and 2) Contributors. 

The Creators and Authors are the people which would be also listed on a corresponding publication, whether this is published or not and do not necessarily require an additional role.  

On the other side, Contributors require a roll, which could be the controlled list from the DataCite metadata schema.

Best,
Tillmann

**Comment by CS76** [comment]
Thanks, @tilfischer, for the detailed explanation. We do have the Datacite Contributor Type implemented for the authors' import. 

<img width="563" alt="image" src="https://user-images.githubusercontent.com/4065285/203523772-0911c883-8fca-4883-86ec-b953bdf0f324.png">

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/4065285/203524005-df71caad-86e8-4e60-8351-5bad28042306.png">

Regarding the 1) Creators and Authors and 2) Contributors differentiation @NRayya, could you please follow this up?

**Comment by NRayya** [comment]
Hi @tilfischer 
This point is something we discussed a lot internally in nmrXiv. We have several points to balance between: Making things simple to the user, comply to datacite, and comply with the rest of repos in NFDI4Chem.

Our approach is to assign "creator" to every one added in the authors section, and additionally, we assign them the role "researchers" as a contributor. The later can be modified by the user to assign other contributors roles. By providing a default, we don't need to request the user to enter roles manually, and this approach is close to the one done in Chemotion.

We will clarify in the UI that every author is a creator and researcher by default to the users. I guess the only problem is if we want to assign more than one contributor role.

Could you please provide us with links or the outcome of the repos in NFDI4Chem discussions? 

Thanks

**Comment by NRayya** [comment]
Closed in favor of further discussion https://github.com/NFDI4Chem/nmrxiv/discussions/630
