### ISSUE TITLE
citations: abstracts and citation text

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#632]
Under "Citation" nmrXiv asks the users to provide a DOI and citation text. Moreover, it requires a title, authors and abstract of the thing to be cited.

Why does nmrXiv requires users to provide an abstract and also askes for the citation text? What is a "citation text" or what does nmrXiv askes for by asking for a "citation text"?

To require an abstract is dangerous with respect to copyright issues. Abstracts might be copyright protected, as long as they are not open access. While adding a citation to a corresponding scientific publication in a scientific journal, authors might copy over the abstract of this scientific publication. This would be ok in the UK, as the Copyright, Designs and Patens Act 1988 allows to copy an distribute abstracts of articles in scientific journals. However, in other countries, including the country where nmrXiv is hosted, this is a copyright violation. The majority of publishers do claim copyright on abstracts.

Suggestions on that would include 1) not to have the abstract required but optional 2) rename this somehow, so that authors do not violate copyright unintentionally. My suggestion: Remove the entire field, as it is not clear, which this is useful in nmrXiv.

Best,
Tillmann

**Comment by NishaSharma14** [comment]
@tilfischer Citation Text is a combination of
`journal title + year of publication + volume + (issue) + page info` e.g. - `Magnetic resonance in chemistry : MRC 2018 56 ( 8 ) 703-715`

I will update the placeholder text for the user to understand easily.

**Comment by tilfischer** [comment]
The question with that is, that there are different styles people use to write such references. Which style should be followed? What is the use case of citation text in nmrXiv?

**Comment by tilfischer** [comment]
Thank you Nisha!

There are two aspects left: 
- nmrXiv askes for the abstract, which is dangerous coz of legal issues also if it is optional. What is the use case of asking for abstract of a citation in nmrXiv? Another way around might be to rename it to "description", but the use case of such a description is also not clear.
- The use case of citation text is still not clear and how to handle different styles. To provide a template is also a bit fuzzy. Way around would be to have separate fields for journal title, year, publication, volume, issue and page, as with authors, title and DOI.

**Comment by CS76** [comment]
@tilfischer 

- Our motivation for asking abstract and other details is to provide a preview of the scientific publication before the user actually clicks the link and is taken to a different page for the full content. 

- Citation text: This is inherited from the DOI imports we currently offer and is optional. The reason we still have this in place is to allow the users to add any other metadata in case the publication is in its pre-print stage or preparation (and doesn't have a DOI yet) as a placeholder.

Adding citation details to the nmrxiv project is optional, and we expect the submitter to add these after the data is archived (after publishing the content on nmrxiv. DOI's generated from nmrxiv is expected to be part of the scientific publication, source of the experimental raw data/output etc.).

**Comment by NishaSharma14** [comment]
![image](https://user-images.githubusercontent.com/54287612/203996631-f09f6674-584c-454f-adcf-a62bdf98e5d8.png)

**Comment by tilfischer** [comment]
Thank you Chandu for the clarification! 

If the use case is solely a preview, than I would definitely suggest to remove the field "abstract", due to the possible copyright violations. Having information like title, authors, journal, year, volume, (issue) and page would be sufficient.  

Other aspects:
- For the use case Chandu described (data not published yet; preprint or preparation) we could recycle the "abstract" field but call this differently e.g. "note" or "comment". Or one might take a drop-down list to chose something and possibly following DataCite's ResourceType with subproperty resourceTypeGeneral.
- for "Authors" and also "Citation Text" one could pick the template, other people would thing that this is strange to them and report this info in another style. Than nmrXiv will end up with a bit chaotic data. How to prevent this? A solution could be to ask separately for every author. This is how it is done in Chemotion Repository and also in RADAR.

In Chemotion Repository this information is provided via "My Collaboration" and the people listed there might be added to a data publication as creators. Please note that Chemotion Repository also gets information there on affiliations but does not separate between given name and family name. Instead this resembles ORCID's published name.

![nmrXiv_citations](https://user-images.githubusercontent.com/85482437/203997769-535c2dfe-be2c-416f-befa-23a8823dc03b.PNG)

In RADAR everything is asked separately. 

![nmrXiv_citations2](https://user-images.githubusercontent.com/85482437/203998093-23e7b0f2-d420-479c-82cd-869eb83e7317.PNG)

**Comment by NishaSharma14** [comment]
#714
