### ISSUE TITLE
Licenses picked from the list doesn't correspond to the viewd ones in local

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#641]
on my local instance which corresponds to development branch without any changes, when I pick a license for a project, another one gets assigned. If I pick the first license in the list, the one assigned is the first one provided in the license seeder: https://github.com/NFDI4Chem/nmrxiv/blob/main/database/seeders/LicenseSeeder.php

https://user-images.githubusercontent.com/82588017/204543569-cc579b7c-64b0-4a19-a170-e7595c502bca.webm

**Comment by NishaSharma14** [comment]
@NRayya, This works perfectly fine in the dev and prod instance. 
What I would suggest is.
- pull the latest code from dev.
- re-run migration with seed `./vendor/bin/sail artisan migrate:refresh --seed`
- and retry this once again.
