### ISSUE TITLE
Addition of multiple authors at once not possible

### ISSUE THREAD

**Issue by tditfe** [NFDI4Chem/nmrxiv#646]
**Describe the bug**
Under "manage authors" you can import the author information with the ORCID. Doing so enables two buttons "Add all" and "Add selected". This implies you can add multiple authors at a time, however importing a second author overwrites the first entry.

**To Reproduce**
1. Click on a project 
2. Click on Edit  (under Author)
3. Click add author
4. Copy and Paste a valid ORCID 
5. Click Import
6. Copy and Paste a second valid ORCID
7. Click Import
8. The previouse entry gets overwritten 

**Expected behavior**
A second (new) entry should be created so you can add multiple entries at the same time.  

**Screenshots**

![Screenshot (21)](https://user-images.githubusercontent.com/116734554/204804812-5c6ae1a1-4789-4a14-9e4d-28d162cb03b4.png)

**Desktop (please complete the following information):**
Win 10 Pro Version 21H2
Firefox 107.0 (32-Bit)

**Comment by NishaSharma14** [comment]
Dear @tditfe ,
This is not a bug. 
For each import, you must click the Add button, to add your entry to the list.

**Comment by tditfe** [comment]
Well I guess this is the classic dilemma, bug or feature xD...sorry for the mislabel i am quite new the whole writing an issue thing.

But you are saying this is supposed to work this way? The problem i am trying to convey is that you have two buttons both of which imply that i can add multiple authors (entries) to the list in one go. So i guess the way to avoid the confusion is simple get rid of one button and relabel the other button to "add"

**Comment by CS76** [comment]
@NRayya update on this please?
