### ISSUE TITLE
Site wide announcements (Dev Tutorial)

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#65]
Description: 
Users with a specific role(s) should be able to access an announcements page in the console and create an announcement to be active from a start date to an end date. A scheduled task should check the time interval and set it as active or inactive (admins should also be able to override the start date). When an active announcement is available the information is then passed on to the front end (App layout) to be displayed on all pages. The user should be able to dismiss the announcement (tracked via local storage) and then the announcement is not shown for the user.

Implementation steps
- [x] #66
- [x] #67
- [x] #68
- [x] #69
- [x] #70
- [x] #71
- [x] #72
- [x] #73
- [x] #96 
- [x] #27

**Comment by NishaSharma14** [comment]
Branch - **side-wide-announcement**
All commits -  https://github.com/NFDI4Chem/nmrxiv/commit/7c29aa49a9580af7d7efbc3bd46e86b110cfcdbc
