### ISSUE TITLE
harmonize project and study view

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#652]
The order of the buttons and the icons are not the same in the project and the study

project:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/82588017/205211232-03232662-8a90-467b-86a3-ad7223713418.png">

study: 
<img width="550" alt="image" src="https://user-images.githubusercontent.com/82588017/205211282-2fd2bf7a-aad6-436d-87f5-6164a9bf4903.png">

**Comment by NishaSharma14** [comment]
Fixed 

Project
<img width="1129" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/54287612/af594082-35fb-42ed-a8ed-9f1b5ba61706">

Study
<img width="916" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/54287612/20dea5e7-2ff2-484a-a2a6-c08cd60015ea">
