### ISSUE TITLE
authors sort - reload needed

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#654]
After sorting the authors in "Manage Authors" window and closing, this sort is not reflected in the project until refreshing the page.

**Comment by NishaSharma14** [comment]
@NRayya, This works fine for me, Can you please specify more if you are expecting something else?

[screen-capture (4).webm](https://user-images.githubusercontent.com/54287612/205601974-7511ecdd-7e25-4d5b-81d1-74a384335f6f.webm)

**Comment by NishaSharma14** [comment]
> It seems there is some sort of inconsistency, I wasn't always able to regenerate the issue [screen-capture.webm](https://user-images.githubusercontent.com/82588017/206190346-85eec1e6-0543-4c77-8cb9-f00599e3ba23.webm)

Can you please this project with me?

**Comment by NishaSharma14** [comment]
@NRayya , Please test this in dev.

**Comment by NRayya** [comment]
Works for me
