### ISSUE TITLE
accounts management - deactivated emails

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#659]
We need to come up with a strategy to handle accounts with deactivated email addresses. This is particularly problematic as many researchers will use uni emails to upload data.  

One solution could be to ask for an alternative email/nmrXiv account to pass ownership to when emails are deactivated. But this will require a regular check for active emails on nmrXiv.

**Comment by NishaSharma14** [comment]
We have to deal with this via ticket. 
For now, if this case arises user can contact our helpdesk and the super admin can take care of it.
