### ISSUE TITLE
Author Role description

### ISSUE THREAD

**Issue by tditfe** [NFDI4Chem/nmrxiv#664]
Just a minor design fix. When you select a Role e.g. Researcher in the "Manage Authors" tab (see screenshot) the description of the role is not fully displayed for me. This is less of issue since you can read it in he "manage role" tab, but i still think it would be nice to be able to read the full description even in this tab. 

p.s. Just in case this is purely a display issue due to the actual monitor/settings i am using. My monitor: Miracube G240S (1920x1200), landscape mode, 100% scaling. 

![Screenshot (22)](https://user-images.githubusercontent.com/116734554/206176047-bc864624-ca6e-43a9-9d40-379a960bb0ee.png)

**Comment by NRayya** [comment]
Thanks for your feedback @tditfe, we will check if there is a problem and fix it soon
