### ISSUE TITLE
Shouldn't Citation info also include all member's name?

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#665]
I have created a project under a team that had members added to it, and also shared the project with some users.
Shall we not include their name in the citation info tab?
Right now we are just including the name of people added as authors.

![image](https://user-images.githubusercontent.com/54287612/206179498-7cfd784f-226d-4e1d-b86a-56f54a572e8c.png)

![image](https://user-images.githubusercontent.com/54287612/206179243-356d462d-cb19-4f39-a685-823c14d8ba49.png)

**Comment by NRayya** [comment]
Closed in favor of https://github.com/NFDI4Chem/nmrxiv/issues/949
