### ISSUE TITLE
Bioschema metadata discussion in the biohackathon

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#672]
- Project
  - [x] conform to ISA
- Study
  - [x] conform to ISA
  - [x] Re-define the structure the output json. May be the study details can be displayed first followed by project and dataset details. May be `isPartOf` is something we can use.
-  [Dataset](https://bioschemas.org/profiles/Dataset/1.0-RELEASE)
  - [x] use  "[variableMeasured](http://schema.org/variableMeasured)"  for NMRium info and results

**Comment by NishaSharma14** [comment]
**BioSchema Markup**
Rene implemented this in https://github.com/MassBank/MassBank-web/commit/44790c61edaeec2f81dc2ea4d9651b561e7d5143
using the Java GSON library for proper encoding. For PHP there could be the equivalent  https://github.com/tebru/gson-php

**Comment by NishaSharma14** [comment]
Other Bioschema Validator tool - 
https://bioschemas-validator.herokuapp.com/  - sometimes down
The code is in https://github.com/ElixirTeSS/bioschemas-validator and how to run the web app locally is mentioned in https://github.com/ElixirTeSS/bioschemas-validator/issues/7#issuecomment-1265385655

Note that there are the branches main, web and develop, with various states of working.

**Comment by NishaSharma14** [comment]
@NRayya if this is something could be helpful to you 
https://github.com/ElixirTeSS/bioschemas-validator/tree/main/profile_json

**Comment by NishaSharma14** [comment]
In case you want to join the main channels for Bioschemas, which would be a good idea to follow the community discussions and so:
[Subscribe](mailto:public-bioschemas-request@w3.org?subject=subscribe) to the mailing list
Get involved in discussions on [GitHub](https://github.com/Bioschemas/specifications/issues)
Join the [slack space](https://join.slack.com/t/bioschemas/shared_invite/zt-1lxfiokgw-q6OENJpDv2suZrDMaNPFjg)
There is also a community call once a month and reminders will be sent to the mailing lists

**Comment by NRayya** [comment]
Using the fair checker: https://fair-checker.france-bioinformatique.fr/check with the end point https://dev.nmrxiv.org/api/v1/schemas/bioschema/

The result was: 
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/82588017/207595613-e601ead1-f899-4475-bb32-9856be208414.png">

Many of the principles are actually met, which requires more discussion in the hackathon

**Comment by NRayya** [comment]
closed in favor of  Bioschema controllers and API #698 
https://github.com/NFDI4Chem/nmrxiv/issues/697
https://github.com/NFDI4Chem/nmrxiv/issues/696
