### ISSUE TITLE
Import CENAPT 

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#673]

**Comment by NRayya** [comment]
Related to https://github.com/cheminfo/nmrium/issues/1775

**Comment by CS76** [comment]
https://s3.uni-jena.de/nmrxiv/production/archive/fd127472-6962-46ad-9390-8ae9e0ad3000/%20Glycyrrhizin%20900MHz%20400MHz%20DMSOd6%20NMR%20data%20.zip

<img width="824" alt="Screenshot 2023-11-21 at 21 32 44" src="https://github.com/NFDI4Chem/nmrxiv/assets/4065285/65847dd5-de77-4347-b003-f79f57a54638">

**Comment by CS76** [comment]
https://s3.uni-jena.de/nmrxiv/production/archive/2cd25088-4513-40ad-8aa6-21ff1f4e3527/%20Lupeol%20900MHz%20400MHz%20CDCl3%20NMR%20data%20.zip

<img width="776" alt="Screenshot 2023-11-21 at 21 37 35" src="https://github.com/NFDI4Chem/nmrxiv/assets/4065285/49738c03-9443-4427-a956-d0e3af2aef72">

**Comment by hamed-musallam** [comment]
it should be fixed https://github.com/NFDI4Chem/nmrium-react-wrapper/pull/169

**Comment by hamed-musallam** [comment]
@CS76 @NRayya 

Could you test and give me feedback?

**Comment by CS76** [comment]
@hamed-musallam This is fixed. Thanks a lot for resolving this. @NRayya we can go ahead and publish this.
