### ISSUE TITLE
link to submission guidelines leads to documentation start page

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#675]
The little book icon on the top right has tooltip "Submission guidelines" but links to https://docs.nmrxiv.org/ rather than https://docs.nmrxiv.org/docs/category/submission-guides

Option 1: Change the tooltip to "Documentation"

Option 2: Change the link to https://docs.nmrxiv.org/docs/category/submission-guides

**Comment by NishaSharma14** [comment]
Fixed in [dev](https://dev.nmrxiv.org/).
