### ISSUE TITLE
Project sharing - invitation emails not received from the first round

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#682]
when a user wants to invite others to teams or projects, they send an email. In many cases, the email remains pending without the receiver actually receiving the email. The sharing user needs to cancel the invitation and send it again in order to actually sending it.

**Comment by NishaSharma14** [comment]
@NRayya I have tested this & it is working as expected.
Please re-test this once again to verify. For now I am closing this issue
