### ISSUE TITLE
citations -  Citation Text placeholder is cut

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#694]
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/82588017/209892610-e03a6398-c424-4cd4-b36c-7086378e1360.png">

**Comment by NishaSharma14** [comment]
It can be extended this way.

[screen-capture (1).webm](https://user-images.githubusercontent.com/54287612/209922358-c65dbc6a-b1d4-4b6f-ab43-0df47aeb953b.webm)

**Comment by NRayya** [comment]
I was thinking that the default size of the field must fit to the placeholder. If you believe that it is not needed please close the issue @NishaSharma14

**Comment by NishaSharma14** [comment]
> I was thinking that the default size of the field must fit to the placeholder. If you believe that it is not needed please close the issue @NishaSharma14

agree..
