### ISSUE TITLE
Front-end Bioschema markup - search engine findability

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#696]
currently we only have the metadata export, we still need to map our objects to bioschema types to enhance their findability by search engines.

**Comment by NRayya** [comment]
Rene implemented this in https://github.com/MassBank/MassBank-web/commit/44790c61edaeec2f81dc2ea4d9651b561e7d5143
using the Java GSON library for proper encoding. For PHP there could be the equivalent https://github.com/tebru/gson-php

**Comment by NishaSharma14** [comment]
Related #697 #698

**Comment by CS76** [comment]
<img width="922" alt="Screenshot 2023-11-13 at 13 08 09" src="https://github.com/NFDI4Chem/nmrxiv/assets/4065285/11d63d38-8921-40c8-a3b5-466dd780168d">
