### ISSUE TITLE
Add Announcement Controller / Actions / Frontend Pages to manage announcements

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#70]
Add controller: https://laravel.com/docs/8.x/controllers
Inertia / Jetstream: https://jetstream.laravel.com/2.x/stacks/inertia.html

**Comment by NishaSharma14** [comment]
Branch - **side-wide-announcement**
All commits -  https://github.com/NFDI4Chem/nmrxiv/commit/7c29aa49a9580af7d7efbc3bd46e86b110cfcdbc
