### ISSUE TITLE
Citations - enable linking to studies

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#703]
Currently the citations are added to the project, which makes it unclear which citation belongs to which study. We need a way to map them.

**Comment by CS76** [comment]
Currently 
> Project - Citation (one to many)
> Study (sample) - Citation (many to many)

citation_study table
- citation_id
- study_id

Add any other pivot columns?? if necessary

UI: Add a dropdown (shows the study names) to the add/edit citation views. User should be able to select the study the citation is referring to.

**Comment by CS76** [comment]
Closing this for now.
