### ISSUE TITLE
manage studies: the name has already been taken

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#705]
Hello,

went to dashboard, selected a project, selected "+Manage Studies", deleted studies and added data and received this error:

![nmrXiv_Pulegon_name_has_already_been_taken](https://user-images.githubusercontent.com/85482437/210801208-e6fe89ce-b5dd-42ec-9557-7da0ad028f21.PNG)

After changing the project name things went fine. However, changing of project name while actually managing studies is possibly not the expected behavior. 

Best,
Tillmann

**Comment by NRayya** [comment]
Hi @tilfischer 
I didn't manage to reproduce the bug, could you please re-check?

**Comment by tilfischer** [comment]
This problem seems to be resolved, hence, I couldn't reproduce just some minutes ago. However, nmrium is still painfull slow.

**Comment by NRayya** [comment]
We are working with NMRium team on it. Thanks for reporting
