### ISSUE TITLE
NMRium loading forever

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#706]
Hello,

following up on #[705](https://github.com/NFDI4Chem/nmrxiv/issues/705), I changed the name of the project and tried to proceed. From [#2005](https://github.com/cheminfo/nmrium/issues/2005) in the NMRium repo I know that NMRium actually only takes the processing data present in the dataset but does not process the FID itself. Hence, one should expect to see the FID, if this processing data is not available in the dataset. 

Unfortunately, the next page (step 2 of 3) loads forever, hence, I am not able to repeat the processing in NMRrium and finally publish the sample. 

![nmrXiv_Pulegon_loading_forever](https://user-images.githubusercontent.com/85482437/210802767-f24d5a90-7a6b-4e2e-b4a3-6a0064a7ff4b.PNG)

Any hints on that?

**Comment by tilfischer** [comment]
Possibly this is connected to datasets not having the spectrum data in 1i/1r files under pdata/1/ . However, I was able to at least get the FID shown before, while it currently loads forever.

Only workaround for now is not to upload the data in Bruker fromat but in JCAMP-DX format generated with MNova, which is neither best-practice nor practical from the viewpoint of a researcher.

**Comment by NRayya** [comment]
Hi @tilfischer 
Thanks for reporting this, could you please send me the data you are uploading?
 in the meantime when you face this issue, reload the page which will take you to the dashboard, from there find the project and continue editing it.

**Comment by karillio** [comment]
Having the same issue at https://dev.nmrxiv.org/ with the example data from the docs page (`Linalool_NMRdata_900MHz_CDCl3_Bruker.zip`)

**Comment by karillio** [comment]
![image](https://user-images.githubusercontent.com/16083968/212395694-dbc8b559-d1cd-4ec1-88bc-4ccebf320d15.png)

**Comment by tilfischer** [comment]
I tried this with another dataset than mention in this issue before. As ever, I used NMR data from https://dx.doi.org/10.22000/785 or https://dx.doi.org/10.22000/786.

**Comment by NRayya** [comment]
Hi @karillio and @tilfischer 
Thanks for reporting the issue. We also have faced and reported it to NMRium team, https://github.com/cheminfo/nmrium/issues/2053.

We will have it fixed soon in nmrXiv when we have the new release of NMRium

**Comment by tilfischer** [comment]
Yes it does!
