### ISSUE TITLE
Meilisearch indexes are deleted after docker restart on local dev

### ISSUE THREAD

**Issue by karillio** [NFDI4Chem/nmrxiv#710]
**Describe the bug**
Dear dev team. 
After docker is down indexes are deleted for some reason.
I mean after commands like: 
`docker-compose down && docker-compose up -d`   

But data from the other volumes like `pgsql` is not deleted. 
Is it possible to leave indexes untouchable? Do you know why this is happening? 
At the moment need to create search indexes every time after docker restart. 

**To Reproduce**
`docker-compose down && docker-compose up -d`   

**Expected behavior**
Search indexes will stay after docker-compose restart. 

**Desktop (please complete the following information):
- OS: Win10
- Google Chrome v108.0.5359.125

**Additional context**
I forked the repo and try fresh install with docker-compose.
Containers started and seems to work.
I try to upload folder structure as a project draft. Here I meet problems.

**Comment by NishaSharma14** [comment]
Thanks @karillio, Can you plz share the script?

**Comment by karillio** [comment]
Hi, 
Do you observe this problem as well? 
Here it the script:

```bash
#/bin/sh

php artisan scout:import "App\Models\FileSystemObject"
php artisan scout:import "App\Models\Project"
php artisan scout:import "App\Models\Study"
php artisan queue:work --queue=scout
```
