### ISSUE TITLE
commands are needed for the fresh installation to run

### ISSUE THREAD

**Issue by karillio** [NFDI4Chem/nmrxiv#712]
**Describe the bug**
Dear dev team, 
I try to run fresh installation, and found that there are commands that one should run to have it working: 

```
php artisan horizon:publish
php artisan storage:link
```
maybe there are some more ?  (I also could miss this info from the documentation, sorry )

**To Reproduce**
Start fresh installation. 

**Desktop (please complete the following information):
- OS: Win10
- Google Chrome v108.0.5359.125

**Additional context**
I use `development` branch. 
I forked the repo and try fresh install with docker-compose.
Containers started and seems to work.
I try to upload folder structure as a project draft. Here I meet problems.

**Comment by NishaSharma14** [comment]
@karillio Can you plz help with why we need this command  `php artisan storage:link` ?

**Comment by karillio** [comment]
Hi @NishaSharma14 , 
I am not sure exactly now anymore. If I remember correctly I did not have minio on local docker-composer installation. 
Then I needed to set `FILESYSTEM_DRIVER=local` and then I was needed to have this command to have my profile image working. It seems to be very special case with this variable, so probably ignore it.
