### ISSUE TITLE
Error "Please upload spectral data to proceed" when data is already there. 

### ISSUE THREAD

**Issue by karillio** [NFDI4Chem/nmrxiv#713]
**Describe the bug**
Dear dev team, not sure if this is a bug, but will post here. 

**To Reproduce**
See additional context info below. 
So I start to upload my data folder. 
For some reason I need to directly open folders with datasets because otherwise I get an erorr: 
**"Please upload spectral data to proceed"** (see image 1), although it is there, just not opened. 
With opened items I could go to the next part (see image 2). 

**Expected behavior**
No error appears, because spectral data is already uploaded.

**Screenshots**

**Image1**: 
![FileBrowserDrafts](https://user-images.githubusercontent.com/16083968/211351043-62db6d15-ebd2-452a-b710-dc78fc3d7ec2.jpg)

**Image2**: 
![FileBrowserDraftsFix](https://user-images.githubusercontent.com/16083968/211351086-f7ae5bb3-a19f-42db-b58e-696ec0fb9296.jpg)

**Desktop (please complete the following information):
- OS: Win10
- Google Chrome v108.0.5359.125

**Additional context**
I use `development` branch. 
I forked the repo and try fresh install with docker-compose.
Containers started and seems to work.
I try to upload folder structure as a project draft. Here I meet problems.

**Comment by NRayya** [comment]
Hello @karillio 
Thanks for reporting the error, could you please try the folder structure described here https://docs.nmrxiv.org/docs/submission-guides/submission/folder-structure ? We understand it is a bit not intuitive, but we need our users to stick to it to make sure we have the same understanding of project/study/dataset.

But we still need to change the error message

**Comment by karillio** [comment]
Hi @NRayya , thank you. You are right, I added one unnecessary level to the structure. 
Now it works 

![image](https://user-images.githubusercontent.com/16083968/211788557-dfad888a-c807-4b80-9741-05fabc103488.png)

**Comment by CS76** [comment]
@karillio We are automatically converting the folder structure into Project > Study (sample) >  Spectra datasets

To enable this, we need the spectra to be organised and uploaded in folders.  I do understand that this requirement currently needs to be clarified. We are working on a solution to overcome this  -   https://github.com/NFDI4Chem/nmrxiv/issues/722

**Comment by karillio** [comment]
Thank you. The issue is clear now. I would close it.
