### ISSUE TITLE
Pass any active announcement details to the Front end (inertiajs)

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#72]
Backend to frontend communication: https://jetstream.laravel.com/2.x/concept-overview.html

**Comment by NishaSharma14** [comment]
Branch - **side-wide-announcement**
All commits -  https://github.com/NFDI4Chem/nmrxiv/commit/7c29aa49a9580af7d7efbc3bd46e86b110cfcdbc
