### ISSUE TITLE
Emails sent to the super-admins should have the user name instead of "admin"

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#721]
The "Dear admin" should be replaced by the user name in the email sent to the super-admins. Also, could you format the content in separate lines?

Project details
Name - Project-test-publish-12-17-2022 
ID - 30

![image](https://user-images.githubusercontent.com/4065285/212000189-d8676ca9-1e68-41d1-bf82-7a3bc215e555.png)

**Comment by NishaSharma14** [comment]
@CS76 I think addressing as `admin` makes clear that this mail is for admin purposes and not personal.
