### ISSUE TITLE
Spectra name - Provide spectra type without refreshing

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#725]
Currently we show the types of the spectra (1H, 13C..) in the spectrum name. However this requires the user to refresh the page to get these details.

Before refresh:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/82588017/212032627-3aefcbf2-758a-4c19-8140-23f3160317d6.png">

After:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/82588017/212032983-1574050b-1abd-452f-a1f5-a14abfe5ce30.png">

**Comment by CS76** [comment]
Also add the nucleus details in addition to the spectra type
