### ISSUE TITLE
Add announcement banner / notification component to display

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#73]
Inertia components: https://jetstream.laravel.com/2.x/stacks/inertia.html#components
Vue3 components: https://v3.vuejs.org/guide/component-basics.html
Tailwind: https://tailwindui.com/components/application-ui/overlays/notifications

**Comment by NishaSharma14** [comment]
Branch - **side-wide-announcement**
All commits -  https://github.com/NFDI4Chem/nmrxiv/commit/7c29aa49a9580af7d7efbc3bd46e86b110cfcdbc
