### ISSUE TITLE
Out of sync issues with deleted spectra (files) and spectral datasets

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#738]
When you delete uploaded studies and then you cancel the deletion, they appear deleted or not deleted in different places of the project.

To reproduce:

1. Submit a project
2. Go to manage studies
3. delete a dataset
4. **Cancel** 
5. Go to the study view 
6. You will find the deleted spectrum in the list of "select spectra" (expected behavior as we canceled the deletion)
7. Go to the files tab, you will not find the deleted spectrum there (**un**expected behavior as we canceled the deletion)

[screen-capture (2).webm](https://user-images.githubusercontent.com/82588017/212218190-4f5cdbc5-34d2-46a0-9962-26a560515810.webm)

**Comment by CS76** [comment]
No longer relevant. Closing this now.
