### ISSUE TITLE
Enable mass deletion of files

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#739]
In the submission pipeline, if you want to select multiple files/folders and delete them at once, this is not possible and only on file/folder gets selected. We need to be able to select more.

[screen-capture (3).webm](https://user-images.githubusercontent.com/82588017/212218816-40b208c8-2daa-4d7d-8cd2-128f2ea7b31d.webm)

**Comment by NishaSharma14** [comment]
Closing in favor #211
