### ISSUE TITLE
publish with embargo

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#760]
Dear all,

publishers in highly competitive fields of chemistry might like to publish their data, while not allowing instantaneous access to that data. In this case, researchers might choose an embargo period or specify a date the dataset gets published. Within the timeframe of that embargo period, the published dataset should have an DOI, to reference in a corresponding scientific publication, but may not be accessed. 

This is already implemented in nmrXiv. What I couldn't find is a feature to release a dataset to the public while still being under embargo or the possibility to extend the embargo period. Is this planed or even already implemented?

Moreover, there could be a feature to request access during the embargo period. Than, the submitter might decide to grant the access or not. This could be also a feature for dataset with infinite embargo period, which might be required if the data contains sensitive information, which should not be available to the public.

Best,
Tillmann

**Comment by tilfischer** [comment]
Please always remember: The usuals phrase used is "publish with embargo" -> its published -> it has a resolvable DOI with a landig pange and DOI metadata -> the date is published but not accessible yet. 

(I think this is the case already in nmrXiv).

**Comment by NishaSharma14** [comment]
Partially done. Can be closed when #973 is closed.

**Comment by NishaSharma14** [comment]
This feature is done and is deployed to prod. Complete demo is in the small clip below.

[screen-capture (24) (1).webm](https://github.com/NFDI4Chem/nmrxiv/assets/54287612/fdf3214b-7bf5-4e65-b1fc-c3e8a95de25c)

**Comment by tilfischer** [comment]
Sounds good! Thank you!

PS: The video is very blurry. I couldn't actually read anything.

**Comment by NishaSharma14** [comment]
Sorry for that, GitHub does not allow uploading gifs/videos of more than 10 MB in size, so the quality got blurred after compression.
