### ISSUE TITLE
retrieve DOI before a project gets published

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#762]
Dear all,

nmrXiv currently registers a DOI with a DOI registration agency when a project gets published. Nonetheless, there might be use cases where researchers might like to retrieve a DOI(s) before a dataset(s) gets published e.g. if they want to provide this DOI in a manuscript (in data availability statement or references) they are planning to submit to a scientific journal. During the review process, other ways than via DOI to provide access to a dataset might be considered (see #761).

One might argue that a dataset in nmrXiv might be published with an embargo period, gets a DOI, which is than added to the manuscript. What happens if the manuscript is rejected and the researcher elects not to publish the data, while he has already published it with an embargo period (please also see #760)?

Best,
Tillmann

**Comment by CS76** [comment]
Apologies for the delay in response here.
We already have the feature implemented @tilfischer. But its not exposed in the UI. WIP now.

Linked to #971

**Comment by CS76** [comment]
> One might argue that a dataset in nmrXiv might be published with an embargo period, gets a DOI, which is than added to the manuscript. What happens if the manuscript is rejected and the researcher elects not to publish the data, while he has already published it with an embargo period

At any stage during the embargo period user can update the release date and extend it further infinitely.

**Comment by NishaSharma14** [comment]
Hi @tilfischer, 
This is done and is deployed to Prod. Please verify it once when you get time.
Closing this issue for now, but if you find some issues plz feel free to create a new one.

Thanks,

**Comment by tilfischer** [comment]
Is the reserved DOI before something got published internally reserved or registered with datacite? If tha latter is the case, which metadata do you add?
