### ISSUE TITLE
import dois from Wiley

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#764]
https://doi.org/10.1002/ciuz.201400660 such dois can't be imported with the current used apis

enable dois import for authors and citations.

**Comment by CS76** [comment]
Use crossref API along with EuropePMC or crossref alone to retrieve details

**Comment by NishaSharma14** [comment]
[screen-capture (19).webm](https://github.com/NFDI4Chem/nmrxiv/assets/54287612/0e4c25cb-e697-4066-affc-f6b553d9ddce)
