### ISSUE TITLE
Authors import - valid orcid raising errors

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#767]
Not all orcid are getting imported, mostly because of the like of affiliation.

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/82588017/217254024-a4916c6f-fa09-4d83-80bf-b66d10913654.png">

For testing: 0000-0001-7881-8345

**Comment by NishaSharma14** [comment]
Improve error reporting when we get empty response for any particular request.

**Comment by NishaSharma14** [comment]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/54287612/221872454-32928f10-d5f3-428f-a09f-cd7020143350.png">
