### ISSUE TITLE
Enable selecting text in author management

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#769]
Currently, only drag and drop is possible to the authors

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/82588017/217262607-e599e8d6-ea16-4286-97b7-99e65ebb64e9.png">

**Comment by NishaSharma14** [comment]
Same fix #773

**Comment by CS76** [comment]
Closing this for now. Will revisit later.
