### ISSUE TITLE
No DOI provided in an easily copyable form

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#773]
Dear all,

I recently published the NMR dataset of pulegon. Today I went on that page https://nmrxiv.org/P16 and tried to copy the DOI as URL to use this in another setting. The DOI of the dataset is shown on top in a badge, if all add blockers are disabled, but cannot be selected and copied. Opening the badge in a new window allows to select the DOI (without the resolver) and reuse it. 

Suggestion: Add a link to the badge including a resolver and the DOI.

Best,
Tillmann

**Comment by CS76** [comment]
<img width="448" alt="Screenshot 2023-11-13 at 11 37 10" src="https://github.com/NFDI4Chem/nmrxiv/assets/4065285/ec1f5f81-a2f1-4472-8a6c-616581d60b00">


DOI badges are now clickable (copies value to clipboard)
