### ISSUE TITLE
import author details from orcid directly

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#774]
Currently we are using other services api's to get the author details from their orcid rather than orcid.org api. For instance, with this orcid: 0000-0001-8171-9399, the affiliation is imported although it is not available on orcid.org. But with this one "0000-0001-8261-9015" it was not imported although it is available, but using the doi " https://doi.org/10.1111/nph.15778" to import all authors with 0000-0001-8261-9015 included give more details. We need to aim for better consistency

**Comment by NishaSharma14** [comment]
ORCID Api do not expose author information explicitly, so we need to stick with europemc API for now.
