### ISSUE TITLE
Authors table - reversed first and last name

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#780]
All the authors entered by importing from orcid have their names revered in the authors table in dev instance. Curation of prod table is needed.

**Comment by NRayya** [comment]
Related to #334

**Comment by NRayya** [comment]
Manual curation 
https://docs.google.com/spreadsheets/d/1Ukl-5vhlMlefZOX4yFvWK62I99B8mh5PCpElb-lt9gk/edit#gid=0

**Comment by NishaSharma14** [comment]
Waiting to be merged in main.

**Comment by CS76** [comment]
@NishaSharma14 update on this please?
