### ISSUE TITLE
Import and export formats to consider for nmrxiv.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#788]
Evaluate and choose the right format.
[Bagit](https://www.rfc-editor.org/rfc/rfc8493) - Chemotion/Radar4Chem supports.
[RO-CRATE](https://www.researchobject.org/ro-crate/)

**Comment by NRayya** [comment]
Evaluation details: https://docs.google.com/presentation/d/1w72LL1qQl27pSHHPIV3uS79tTyZq5LD-c9Eu5cjgXFQ/edit#slide=id.g25304c5fa4f_0_0

**Comment by NRayya** [comment]
Closed in favor of https://github.com/NFDI4Chem/nmrxiv/issues/724
