### ISSUE TITLE
Notifications feature - include old notifications 

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#789]
notifications implemented in the past didn't make use of the new notifications feature, such as send an invitation to join a team

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/82588017/219869850-29620a50-7c22-4727-88ba-a69fab7c488c.png">

**Comment by NRayya** [comment]
#746

**Comment by NishaSharma14** [comment]
Not relevant as these are flash messages for quick confirmation.
