### ISSUE TITLE
Public projects - Window resizing is needed to show DOIs for projects

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#802]
While on the page of an study e.g. https://nmrxiv.org/S83 the DOI 10.57992/nmrxiv.p16.s83 is shown in a badge, although not copyable see #773 , the corresponding project page https://nmrxiv.org/P16 does not show the DOI corresponding 10.57992/nmrxiv.p16 .

DOI of project should be added to UI.

**Comment by NRayya** [comment]
Actually it is shown be resizing of the page is needed. I will change the title of the issue accordingly. Thanks for reporting

**Comment by tilfischer** [comment]
Found it on 133% zoom.
