### ISSUE TITLE
Data download - Missing data 

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#804]
When downloading  a project, sometime not all the studies get downloaded. 
For instance: https://nmrxiv.org/P12

Here we have 7 samples. When downloaded, we get 5 only. Nicotinic acid and Nalidixic acid are missing

Same with this project: https://nmrxiv.org/P9?tab=studies. In both cases, no more than 5 samples downloaded.

**Comment by CS76** [comment]
The issue is due to truncation from the AWS Client. Resolved now with paginator implementation.
