### ISSUE TITLE
DOIs are not getting generated in Dev

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#806]
Got this error in the horizon dashboard.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/54287612/225920324-01f4d51c-b43a-452c-8932-b6f202b2ad59.png">

**Comment by CS76** [comment]
Working on my local setup. Please cross-check data cite credentials and test it again.

**Comment by CS76** [comment]
Credentials issue
