### ISSUE TITLE
Published projects - spectra display is missing from NMRium

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#815]
In the production environment, in the published projects, the spectra are not displayed in NMRium. Example: https://nmrxiv.org/S81 

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/82588017/233351841-19390972-1fd9-499d-97fe-7dc3a2302bad.png">

**Comment by CS76** [comment]
<img width="1159" alt="Screenshot 2023-11-13 at 11 43 29" src="https://github.com/NFDI4Chem/nmrxiv/assets/4065285/06494b99-dcb1-4055-aea6-099ce2a88229">
