### ISSUE TITLE
Registration - Can't use ORCID to register

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#820]
ORCID can only be added to the account, but it can't be used to fetch user details for registration

We want to enable populating the profile details by fetching them by orcid

https://user-images.githubusercontent.com/82588017/234236604-74535dde-7bcf-4b0b-a1ee-dacc4f5fb7eb.mov

**Comment by NishaSharma14** [comment]
Right now you can fetch ORCID-ID from first name and last name but the other way around is not possible.
