### ISSUE TITLE
keywords - adding a comma after a word raises an error

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#826]
commas are used to separate keywords, however, if the user adds a comma accidentally after a word and nothing more, they get an error. The comma should be deleted instead.
 
<img width="1303" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/82588017/ab2490f3-b82d-4272-b04c-44a9a0c81ce1">

**Comment by NishaSharma14** [comment]
Fixed..
