### ISSUE TITLE
Spectra won't display after data upload

### ISSUE THREAD

**Issue by jaminnash** [NFDI4Chem/nmrxiv#831]
**Describe the bug**
When I upload bruker data files, the spectra do not load. At the top of the spectra page it says "Loading Spectra from URL" and then there is an error "There were errors loading spectra. TypeError: Network request failed".

**To Reproduce**
1. Click "upload" it import new data
2. Drag bruker data folder into upload screen and wait for upload to complete

**Expected behavior**
Spectra will load in under the "Spectra" tab

**Screenshots**
![Error Screenshot](https://github.com/NFDI4Chem/nmrxiv/assets/54374286/612694e5-8eae-44b8-9c10-1113cd3243bf)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 114.0.5735.134

**Comment by jaminnash** [comment]
I see that this bug has not been assigned after 2 months. The issue persists. Is there any advice that can be provided to help me with this issue? Thank you.

**Comment by CS76** [comment]
@jaminnash Apologies for the delay in response. Can you please email us the project name and bruker data files you are trying to load to info.nmrxiv@uni-jena.de so we could look into the issue?

**Comment by NishaSharma14** [comment]
Closing this issue as it has been stale for long.
