### ISSUE TITLE
Using NMRium for process .jdf file from a Jeol NMR

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#839]
### Discussed in https://github.com/NFDI4Chem/nmrxiv/discussions/838

<div type='discussions-op-text'>

<sup>Originally posted by **ajmgiraffe** July 27, 2023</sup>
Hi, I am new to this chat, I am trying to process NMR spec from Jeol, so the file type is 'jdf. When I drag and drop, the file is there, but there is no spectra to view, whether the nucleus is on or off - please can someone advise me on how to remedy this issue, or tell me if it can't be remedied? Many thanks, Anthony</div>

**Comment by CS76** [comment]
@ajmgiraffe, can you please provide us more details on which platform are you using the NMRium? Is it on nmrXiv or Chemotion or nmrium.org? Also, it would be helpful for us to debug if you could provide us the jdf file(s) you are facing issues with.

**Comment by ajmgiraffe** [comment]
Hi, Thank you for your response; I have already solved this issue with someone from NMRium. It seemed the software was slightly bugged, but now I can use this fine - thank goodness. Really appreciate you offering your help, no doubt I will be back. Thanks, Ant
