### ISSUE TITLE
Two factor authentication - QR code link broken

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#842]
In the user's account, when enabling two factor authentication, the shown QR code leads to unreachable site when scanned.

**Comment by CS76** [comment]
Can you please confirm you are using an authentication app to scan the QR code ??

2FA QR code must be scanned with an app like Google Auth or Authy. They will then allow you to generate a one-time code from your device and be able to sign in. You may have tried with your camera directly.
