### ISSUE TITLE
Issue with oauth buttons not occupying full width

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#86]

**Comment by NishaSharma14** [comment]
Somehow I see the Twitter and GitHub icon faded than the Orcid.
![image](https://user-images.githubusercontent.com/54287612/167667195-f917ea8a-cea6-4c63-a416-e558fc12e1b6.png)

**Comment by NishaSharma14** [comment]
Changed the logo color.

![image](https://user-images.githubusercontent.com/54287612/168585822-6eb85f63-1c99-4dc4-a2e5-9b0fcfda9a21.png)
