### ISSUE TITLE
Citing nmrXiv datasets - One can only cite their own publications

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#861]
The citing option:
<img width="1181" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/82588017/30910d69-a205-4fc3-8fcc-457737dc2135">
shows only when opening one's own public projects while it doesn't from the public view of pthers projects and spectra:
<img width="1169" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/82588017/9467aebe-9079-444b-a4fa-01a9b9244a2d">

We need to provide it there too

**Comment by CS76** [comment]
![Screenshot 2023-11-13 at 10 22 45](https://github.com/NFDI4Chem/nmrxiv/assets/4065285/11a97eba-57af-43b9-bf68-6563c45db876)

Resolved in #888 pull request
