### ISSUE TITLE
User dashboard - enable opening projects in a new tab

### ISSUE THREAD

**Issue by NRayya** [NFDI4Chem/nmrxiv#864]
Currently projects can only be open in the same tab, while most other parts of nmrXiv work nicely with opening in a new tab. We need to enable that for projects too.

**Comment by CS76** [comment]
Can you be more specific? Which views?? use case

**Comment by CS76** [comment]
<img width="859" alt="Screenshot 2023-11-13 at 11 33 25" src="https://github.com/NFDI4Chem/nmrxiv/assets/4065285/b05d49cf-7221-4ce8-b56f-98ddd3ffb933">
