### ISSUE TITLE
Provide Helm chart for deployment

### ISSUE THREAD

**Issue by sneumann** [NFDI4Chem/nmrxiv#88]
Hi, 
nmrXiv should be deployable using a helm chart. 
This could be based on https://github.com/stefanaz/laravel-helm-chart work. 
Yours,
Steffen

**Comment by NishaSharma14** [comment]
Helm chart repo - https://github.com/NFDI4Chem/repo-helm-charts
Released via Github pages - https://nfdi4chem.github.io/repo-helm-charts/
