### ISSUE TITLE
Deployment to GKE (Development environment)

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#9]
As a developer, I want to perform basic deployment of the project to GKE and complete the setup development enviroment accessible via the below URL.
https://dev.nmrxiv.org/

**Comment by sneumann** [comment]
Hi, as another developer I also want a deployment on my GKE, accessible via a URL of my choice (because dev.nmrxiv.org might already be in use ;-) ) Yours, Steffen

**Comment by NishaSharma14** [comment]
Hi Steffen, Thanks for your interest :-)
Probably we can discuss and get more details on this and your plans.

**Comment by sneumann** [comment]
No special plans, just saying there should be a GKE deployment possible that uses a different domain, maybe even nmrxiv.a.b.c.d.nip.io . Yours, Steffen
