### ISSUE TITLE
NMRium unable to load jdx files from mnova

### ISSUE THREAD

**Issue by CS76** [NFDI4Chem/nmrxiv#918]
Examples:
https://s3.uni-jena.de/nmrxiv/production/archive/a9d8c2a7-fc95-4eb6-84dd-107548aa0c48/12c_HEE296.zip

Error:
<img width="717" alt="Screenshot 2023-11-20 at 20 18 40" src="https://github.com/NFDI4Chem/nmrxiv/assets/4065285/4d2f2034-f0c1-4087-ac25-9cfee11c94cd">

**Comment by CS76** [comment]
Latest nmrium-react-wrapper release should resolve this

**Comment by NRayya** [comment]
Using NMRium dev instance with the folder provided in the issue, the problem seems to be solved
<img width="713" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/82588017/e41565a5-2fc1-4247-bd0c-fe41337acc31">
