### ISSUE TITLE
Enable download of all projects

### ISSUE THREAD

**Issue by michaelwenk** [NFDI4Chem/nmrxiv#924]
It is necessary to make the entire dataset in nmrXiv downloadable at once.

This can be done via API and REST requests and also through a "download all projects" button in the user interface.  
The resulting file should be in an RDF model (e.g. JSON-LD), so that further relationships and knowledge can be extracted.

**Comment by CS76** [comment]
@michaelwenk We could generate this, but it will be a massive file and going forward, considering the data depositions, this will be impossible to maintain.

What I recommend is to be able to traverse all public projects/samples/compounds and be able to download the RDF models for each of these. You can then process and enrich with new data as and when new data is published.

We expose multiple endpoints.

1) List all projects/samples/compounds
2) Retrieve JSON-LD for any of these entities based on the identifier (for example - P123/S123/C1234 etc.)

Let me know if this works.

**Comment by NRayya** [comment]
> List all projects/samples/compounds

We could provide a list of the projects and the studies within and then the datasets within but only as a list of identifiers and using one endpoint

**Comment by CS76** [comment]
> We could provide a list of the projects and



> We could provide a list of the projects and the studies within and then the datasets within but only as a list of identifiers and using one endpoint

Not sure what you are referring to here, can you elaborate??

**Comment by CS76** [comment]
Since the endpoints are already exposed. I suggest we close the issue and open new one if there is any further request. 
@michaelwenk  ??
