### ISSUE TITLE
Add the short version for CC licenses to the list of licenses to choose

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#950]
Dear all,

**Is your enhancement request related to a problem? Please describe.**

After upload of data the user is taken to another page to enter further information such as a description, keywords and many more. On the bottom of that page one needs to select a license. There is a list of many licenses down there but I actually know that I would like to select CC BY 4.0. 

However, this license is described with "Creative Commons Attribution 4.0 International", which is right, but very difficult to find from the drop down list. I initially tried to open the drop down list and searched for "CC BY". This gave not result, as the short version of this license is not available in this list, while searching for "attribution" works, which is great. 

**Describe the solution you'd like**

Please change "Creative Commons Attribution 4.0 International" to "Creative Commons Attribution 4.0 International (CC BY 4.0)". The same applies (at least) to all other CC licenses.

Best,
Tillmann

**Comment by tilfischer** [comment]
Dear Nisha,

thank you for the update. 

Some typo:

CC0-1.0 -> CC0 1.0
CC-BY-NC-SA-4.0 -> CC BY-NC-SA 4.0 
CC-BY-SA-4.0 -> CC BY-SA 4.0
and so on...

Best,
Tillmann

**Comment by NishaSharma14** [comment]
Thanks again @tilfischer, It is rectified now.
Please verify once and close the ticket when you get time.

**Comment by tilfischer** [comment]
Looks fine. Thank you!
