### ISSUE TITLE
Not obvious how to open the right hand panel to access spectra, information ... in NMRium

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#975]
**Is your enhancement request related to a problem? Please describe.**
I uploaded some NMR data, containing 16 samples, 74 spectra and 18 molecules, hence, each sample had many spectra. In Step 2/3, I selected one sample and it displayed the COSY. Well, I would have expected the 1H to show first, but this is an minor and other issue, but I also report this here. Then, I tried to find the 1H and found it, but this was incredibly hidden.

![Screenshot 2023-12-20 224453](https://github.com/NFDI4Chem/nmrxiv/assets/85482437/f9e8e562-1c8d-4638-adc7-d8cd669af586)

It took some time, while this also might be due to the fact that the display of my Acer laptop is has horribly low contrast and only has a resolution of 1920*1080 px. Another reason why it took some time is that if one clicks on the tree dots to the right, nothing happens. Windows users might have an advantage here, as double click helps. This opens the panel to to access other spectra of that sample.

**Describe the solution you'd like**
Have the panel to the left opened as default

**Describe alternatives you've considered**
If the suggested solution is not an option, the three dots should be highlighted somehow. 

Best,
Tillmann

**Comment by CS76** [comment]
Custom workspace - Panels and tools ~ Needs to be specified.

Opened by default
Collapsible through query parameter

**Comment by CS76** [comment]
NMRium issue: https://github.com/cheminfo/nmrium/issues/2782

To address the issue, we have enabled the sidebar to be open by default so users are aware of it.
