### ISSUE TITLE
ordering of spectra within a sample in alphabetical order, capitalisation of NMR methods

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#977]
**Is your enhancement request related to a problem? Please describe.**
From the example in another issue (please ignore the red circle), spectra of one sample in Step 2/3 of the submission process are somehow not ordered and NMR methods aren't capitalized, which is usually the case for acronyms. 

![Screenshot 2023-12-20 224453](https://github.com/NFDI4Chem/nmrxiv/assets/85482437/4344dac7-41c5-4604-a184-50fb0890b15d)

20 (1d - 1H)
24 (hmbc - 1H-13C)
21 (c13 - 13C)
22 (cosy - 1H-1H)
23 (hsqc - 1H-13C)

**Describe the solution you'd like**
20 (1d - 1H)
21 (c13 - 13C)
22 (COSY - 1H-1H)
23 (HSQC - 1H-13C)
24 (HMBC - 1H-13C)

Best,
Tillmann

**Comment by NRayya** [comment]
<img width="275" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/82588017/df5a42c6-1ad8-4c8c-bf02-40b63cdb5bf3">

<img width="263" alt="image" src="https://github.com/NFDI4Chem/nmrxiv/assets/82588017/47d0af38-3a13-4a56-9150-8428506d4e62">
