### ISSUE TITLE
Member with owner role should have option to delete the team.

### ISSUE THREAD

**Issue by NishaSharma14** [NFDI4Chem/nmrxiv#98]
**Describe the bug**
Members added as owners in a team should have an option to delete the team.

**To Reproduce**
1. Go to Team Setting
2. Add a member as owner role.
3. Member accepts the invitation 
4. Member goes to the Team Setting
5. Delete option is not there.

**Expected behavior**
Should have a Delete option.

**Screenshots**
![image](https://user-images.githubusercontent.com/54287612/156543169-79af7e43-ab6b-423c-8bbf-f38630744a36.png)

**Comment by NRayya** [comment]
There are other options not available for the members added as owners, they include:

- [ ] - Changing Team name
- [ ] - Adding new members
- [ ] - Removing members
- [ ] - Canceling invitations

**Comment by NRayya** [comment]
it is still not possible for added members as owners to delete the team

**Comment by NRayya** [comment]
The other functions mentioned on 8 April still don't work

**Comment by NishaSharma14** [comment]
As discussed with @CS76, The owner should not have the option to perform Delete Action. Only the creator of the Team should have the privilege to Delete a Team.
