### ISSUE TITLE
cannot delete any drafts of projects

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#996]
**Describe the bug**
I cannot delete any drafts of projects in any of my team or my personal account: ``It is not possible to delete a project that is currently being processed or queued.`` 

I also tried to process the data up to step 3/3 of the submission process and then tried again to delete the drafts. Same error message.

**Expected behavior**
Delete drafts of projects.

Best,
Tillmann

**Comment by tilfischer** [comment]
Any updates on this? The problem persists. Some LbE Contributors also pinged me on that.

**Comment by CS76** [comment]
@tilfischer It should be resolved on the production site by the end of the day.

**Comment by tilfischer** [comment]
Thank you! Works again, not just for me but also for other users.
