### ISSUE TITLE
Add the resolver to the DOI which is copied to the clipboard

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/nmrxiv#998]
**Is your enhancement request related to a problem? Please describe.**
There is the nice feature to copy the DOI to the clipboard for projects, samples and spectra see:
![Screenshot 2024-01-09 150525](https://github.com/NFDI4Chem/nmrxiv/assets/85482437/a5e02948-8af8-4af1-9bfb-e8d7f8d51a04)

This puts ``10.57992/nmrxiv.p2.s273`` to the clipboard

**Describe the solution you'd like**
I would like to have a resolver added to that DOI e.g. ``https://doi.org/`` or ``https://dx.doi.org/`` as I want to use this to reference a page I want to send to someone and this should be hyperlink. I agree that there are two solutions to this a) I add this manually b) I leave this to the person I send the DOI.

**Describe alternatives you've considered**
If the DOI is there for reasons but not the DOI including a resolve, another button next by should copy the DOI including a resolver to the clipboard.

Best,
Tillmann

**Comment by tilfischer** [comment]
I can confirm that the resolver is added now.

**Comment by NishaSharma14** [comment]
Thanks @tilfischer this issue can be closed now.
